//! Leptos UI for the one-page site. Phase 2: the interactive device.
//!
//! Layout follows the site plan: hero (one-liner + install), the handshake
//! device ("who has to prove themselves?" toggles resolving to a real
//! pattern, replaying its frozen trace), the proof strip, and the install
//! footer. Copy is lifted from the README — the page asserts nothing the
//! crate's docs don't, and every number in the device comes from
//! `fixtures_data.in`, generated by hiss and pinned by a test.

use std::time::Duration;

use leptos::prelude::*;

use crate::fixtures::{self, Dir};

const REPO: &str = "https://github.com/primetype/hiss";
const TESTED: &str = "https://github.com/primetype/hiss#how-this-is-tested";
const PINNED: &str = "https://github.com/primetype/hiss/blob/main/site/tests/fixtures.rs";

// Toggle chip states. Kept as consts so Tailwind's scanner sees every class.
const TG_ON: &str = "rounded-full border border-cyan-dim px-3 py-1 text-xs text-cyan";
const TG_OFF: &str =
    "rounded-full border border-line px-3 py-1 text-xs text-silver-dim hover:border-silver-faint";
const TG_DISABLED: &str =
    "rounded-full border border-line-soft px-3 py-1 text-xs text-silver-faint cursor-not-allowed";

#[component]
pub fn App() -> impl IntoView {
    view! {
        <main class="mx-auto max-w-4xl px-5 pb-24">
            <Nav />
            <Hero />
            <Device />
            <div class="static-band my-10"></div>
            <ProofStrip />
            <PageFooter />
        </main>
    }
}

#[component]
fn Nav() -> impl IntoView {
    view! {
        <nav class="flex items-baseline gap-5 border-b border-line-soft py-5 text-[13px]">
            <span class="text-[15px] font-semibold text-silver-bright">"hiss"</span>
            <a class="ml-auto text-silver-dim hover:text-cyan" href="https://docs.rs/hiss">
                "docs.rs ↗"
            </a>
            <a class="text-silver-dim hover:text-cyan" href=REPO>
                "github ↗"
            </a>
        </nav>
    }
}

#[component]
fn Hero() -> impl IntoView {
    view! {
        <header class="pt-16 pb-10">
            <p class="mb-4 text-[11.5px] uppercase tracking-[0.16em] text-silver-dim">
                "noise protocol framework · rust · sans-io · no async runtime"
            </p>
            <h1 class="max-w-[24ch] text-3xl font-semibold leading-tight tracking-tight text-silver-bright [text-wrap:balance] md:text-4xl">
                "Encrypted, authenticated channels between two peers you control."
            </h1>
            <p class="mt-4 max-w-[52ch] text-[15px] text-silver-dim">
                "You decide who proves themselves — the handshake enforces it, the compiler checks it."
            </p>
            <a
                class="mt-5 inline-block rounded-full border border-warn/50 px-3 py-1 text-xs text-warn"
                href="#proof"
            >
                "unaudited · pre-1.0 — what stands in for an audit ↓"
            </a>
            <div class="mt-6 flex flex-wrap items-center gap-3.5">
                <a
                    class="rounded-sm border border-cyan-dim px-4 py-2 text-[13px] text-cyan hover:border-cyan hover:bg-cyan/10"
                    href="https://docs.rs/hiss"
                >
                    "read the quickstart →"
                </a>
                <span class="rounded-sm border border-line-soft bg-panel px-4 py-2 text-[13px]">
                    <span class="text-silver-faint">"$ "</span>
                    "cargo add hiss"
                </span>
            </div>
        </header>
    }
}

/// A trace row that becomes visible once the sequencer passes step `k`.
#[component]
fn Reveal(k: usize, step: RwSignal<usize>, children: Children) -> impl IntoView {
    let shown = move || step.get() > k;
    let class = move || {
        if shown() {
            "trace-row opacity-100 transition-opacity duration-500"
        } else {
            "trace-row opacity-0 transition-opacity duration-500"
        }
    };
    view! { <div class=class>{children()}</div> }
}

/// The device: three choices resolve to a real pattern; its frozen trace
/// (bytes generated by hiss, pinned by `tests/fixtures.rs`) replays.
#[component]
fn Device() -> impl IntoView {
    let you = RwSignal::new(true);
    let peer = RwSignal::new(true);
    let known = RwSignal::new(false);
    let step = RwSignal::new(0usize);
    let replay = RwSignal::new(0usize);
    let handles: StoredValue<Vec<TimeoutHandle>> = StoredValue::new(Vec::new());

    let name = Memo::new(move |_| fixtures::pick(you.get(), peer.get(), known.get()));

    // The sequencer: on every pattern change (or manual replay), cancel any
    // pending reveals and schedule the trace from the top.
    Effect::new(move |_| {
        let n = name.get();
        replay.track();
        handles.update_value(|v| {
            for h in v.drain(..) {
                h.clear();
            }
        });
        step.set(0);
        let total = fixtures::fixture(n).msgs.len() + 3;
        for i in 1..=total {
            let delay = Duration::from_millis(350 + 550 * i as u64);
            if let Ok(h) = set_timeout_with_handle(move || step.update(|s| *s = (*s).max(i)), delay)
            {
                handles.update_value(|v| v.push(h));
            }
        }
    });

    let on_you = move |_| you.update(|v| *v = !*v);
    let on_peer = move |_| {
        peer.update(|v| *v = !*v);
        if !peer.get_untracked() {
            known.set(false);
        }
    };
    let on_known = move |_| known.update(|v| *v = !*v);
    let on_replay = move |_| replay.update(|r| *r += 1);

    let known_class = move || {
        if !peer.get() {
            TG_DISABLED
        } else if known.get() {
            TG_ON
        } else {
            TG_OFF
        }
    };
    let is_default = move || name.get() == "XX";

    view! {
        <section class="rounded-sm border border-line bg-panel p-4">
            <div class="flex flex-wrap items-center gap-2 pb-4">
                <button
                    class=move || if you.get() { TG_ON } else { TG_OFF }
                    on:click=on_you
                >
                    {move || if you.get() { "● you prove who you are" } else { "○ you prove who you are" }}
                </button>
                <button
                    class=move || if peer.get() { TG_ON } else { TG_OFF }
                    on:click=on_peer
                >
                    {move || if peer.get() { "● peer proves who they are" } else { "○ peer proves who they are" }}
                </button>
                <button
                    class=known_class
                    disabled=move || !peer.get()
                    on:click=on_known
                >
                    {move || if known.get() { "● peer key known in advance" } else { "○ peer key known in advance" }}
                </button>
                <span class="ml-auto text-xs text-silver-dim">
                    "→ " <span class="text-cyan">{move || name.get()}</span>
                    <Show when=is_default>
                        <span class="text-silver-faint">" · the default"</span>
                    </Show>
                </span>
                <button
                    class="text-xs text-silver-faint hover:text-cyan"
                    on:click=on_replay
                    aria-label="replay the handshake"
                >
                    "replay ⟳"
                </button>
            </div>
            {move || {
                let f = fixtures::fixture(name.get());
                let inf = fixtures::info(name.get());
                let last = f.msgs.len();

                let mut you_rows: Vec<AnyView> = Vec::new();
                let mut peer_rows: Vec<AnyView> = Vec::new();
                if let Some(pre) = f.pre {
                    you_rows.push(
                        view! {
                            <div class="text-silver-faint">
                                {format!("{pre}   · peer's key, known in advance")}
                            </div>
                        }
                        .into_any(),
                    );
                }
                for (i, m) in f.msgs.iter().enumerate() {
                    let (arrow, rows) = match m.dir {
                        Dir::ToPeer => ("→ ", &mut you_rows),
                        Dir::FromPeer => ("← ", &mut peer_rows),
                    };
                    rows.push(
                        view! {
                            <Reveal k=i step=step>
                                <span class="text-cyan">{arrow}{m.tokens}</span>
                                <span class="text-silver-faint">{format!("  · {} B", m.size)}</span>
                                <div class="text-[10px] text-silver-faint">{m.preview}</div>
                            </Reveal>
                        }
                        .into_any(),
                    );
                }
                you_rows.push(
                    view! {
                        <Reveal k=last step=step>
                            <span class="text-cyan">"✓ channel open"</span>
                            <div class="text-[10px] text-silver-faint">
                                {format!("session {}", f.session)}
                            </div>
                        </Reveal>
                    }
                    .into_any(),
                );
                peer_rows.push(
                    view! {
                        <Reveal k=last step=step>
                            <span class="text-cyan">"✓ channel open"</span>
                        </Reveal>
                    }
                    .into_any(),
                );
                you_rows.push(
                    view! {
                        <Reveal k={last + 1} step=step>
                            <span class="text-silver">"→ \"ping\", sealed"</span>
                            <span class="text-silver-faint">
                                {format!("  · {} B tag", f.overhead)}
                            </span>
                            <div class="text-[10px] text-silver-faint">{f.ping_ct}</div>
                        </Reveal>
                    }
                    .into_any(),
                );
                peer_rows.push(
                    view! {
                        <Reveal k={last + 2} step=step>
                            <span class="text-silver">"« ping » · ← \"pong\", sealed"</span>
                            <div class="text-[10px] text-silver-faint">{f.pong_ct}</div>
                        </Reveal>
                    }
                    .into_any(),
                );

                let blurb = if inf.caveat {
                    view! { <span class="text-warn">{format!("⚠ {}", inf.blurb)}</span> }
                        .into_any()
                } else {
                    view! { <span class="text-silver-dim">{inf.blurb}</span> }.into_any()
                };

                view! {
                    <div class="grid gap-3 md:grid-cols-[1fr_auto_1fr]">
                        <div class="min-h-40 rounded-sm border border-line-soft bg-ink p-3 text-xs leading-6">
                            <div class="pb-1 font-semibold text-silver-bright">"you"</div>
                            {you_rows}
                        </div>
                        <pre class="overflow-x-auto rounded-sm border border-line-soft bg-ink p-3 text-xs leading-6 text-silver-dim">
                            <code>
                                <span class="text-cyan">"hiss::noise!"</span>
                                {inf.decl}
                            </code>
                        </pre>
                        <div class="min-h-40 rounded-sm border border-line-soft bg-ink p-3 text-xs leading-6">
                            <div class="pb-1 font-semibold text-silver-bright">"peer"</div>
                            {peer_rows}
                        </div>
                    </div>
                    <p class="pt-3 text-xs">
                        <span class="text-silver-dim">
                            {format!("{} messages · ", f.msgs.len())}
                        </span>
                        {blurb}
                        <span class="text-silver-faint">" · "</span>
                        <a class="text-cyan hover:underline" href=inf.explorer>
                            "formal analysis ↗"
                        </a>
                        <span class="text-silver-faint">" · "</span>
                        <a class="text-silver-faint hover:text-cyan" href=PINNED>
                            "real bytes — generated by hiss, pinned by test"
                        </a>
                    </p>
                }
            }}
        </section>
    }
}

#[component]
fn ProofStrip() -> impl IntoView {
    view! {
        <section id="proof" class="flex flex-wrap items-baseline gap-x-2 gap-y-1.5 text-xs">
            <a class="text-silver-dim hover:text-cyan" href=TESTED>
                "17-pattern KATs ✓"
            </a>
            <span class="text-silver-faint">"·"</span>
            <a class="text-silver-dim hover:text-cyan" href=TESTED>
                "Wycheproof 484 + 355 ✓"
            </a>
            <span class="text-silver-faint">"·"</span>
            <a class="text-silver-dim hover:text-cyan" href=TESTED>
                "snow interop ✓"
            </a>
            <span class="text-silver-faint">"·"</span>
            <a class="text-silver-dim hover:text-cyan" href=TESTED>
                "cacophony vectors ✓"
            </a>
            <span class="text-silver-faint">"·"</span>
            <a class="text-warn" href="https://github.com/primetype/hiss#security">
                "unaudited · pre-1.0"
            </a>
            <span class="text-silver-faint">"·"</span>
            <a class="text-silver-dim hover:text-cyan" href="https://noiseexplorer.com/patterns/">
                "formal pattern analyses ↗"
            </a>
        </section>
    }
}

#[component]
fn PageFooter() -> impl IntoView {
    view! {
        <footer class="mt-10 border-t border-line-soft pt-6 text-xs leading-6 text-silver-faint">
            <p class="mb-3">
                "0.2 is unreleased — the 0.1.0 on crates.io predates the "
                <span class="text-silver-dim">"noise!"</span>
                " macro this page describes."
            </p>
            <div class="mb-3 flex flex-wrap gap-x-5 gap-y-1">
                <a class="text-silver-dim hover:text-cyan" href="https://docs.rs/hiss">
                    "docs.rs"
                </a>
                <a class="text-silver-dim hover:text-cyan" href="https://crates.io/crates/hiss">
                    "crates.io"
                </a>
                <a class="text-silver-dim hover:text-cyan" href=REPO>
                    "github"
                </a>
                <a class="text-silver-dim hover:text-cyan" href="https://crates.io/crates/snow">
                    "need more Noise? snow ↗"
                </a>
            </div>
            <p>
                "Apache-2.0 OR MIT · built on the "
                <a class="text-silver-dim hover:text-cyan" href="https://noiseprotocol.org/">
                    "Noise Protocol Framework"
                </a>
                " · report security issues privately to the maintainers, not as public issues."
            </p>
        </footer>
    }
}
