//! Leptos UI for the one-page site: splash + the "find your handshake" wizard.
//!
//! The page is a splash — hero, one big invite, proof strip, footer. The
//! invite opens a modal wizard: three questions resolve to a real Noise
//! pattern, and the result card shows what you gained, the `noise!` code,
//! the pattern's frozen trace replaying (bytes generated by hiss, pinned by
//! `tests/fixtures.rs`), the alternates, and a suite recommendation. Copy is
//! lifted from the README — the page asserts nothing the crate's docs don't.

use std::time::Duration;

use leptos::ev;
use leptos::html;
use leptos::prelude::*;

use crate::fixtures::{self, Dir};

const REPO: &str = "https://github.com/primetype/hiss";
const TESTED: &str = "https://github.com/primetype/hiss#how-this-is-tested";
const PINNED: &str = "https://github.com/primetype/hiss/blob/main/site/tests/fixtures.rs";

/// Answer cards and buttons share these classes so Tailwind's scanner sees
/// them — and so everything clickable unmistakably *looks* clickable.
const ANSWER_CARD: &str = "block w-full cursor-pointer rounded-sm border border-line bg-panel-2 \
     p-4 text-left transition-colors hover:border-cyan hover:bg-cyan/5";
const GHOST_BTN: &str = "cursor-pointer text-xs text-silver-faint hover:text-cyan";
const TAB_ON: &str =
    "cursor-pointer rounded-sm border border-cyan bg-cyan/10 px-3 py-1.5 text-xs text-cyan";
const TAB_OFF: &str = "cursor-pointer rounded-sm border border-line px-3 py-1.5 text-xs \
     text-silver-dim transition-colors hover:border-silver-faint hover:text-silver";

/// rustc's rejection of a pattern that never keys the cipher — the Noise
/// §7.3 guard. Quoted from the README, where it is pinned by a
/// `compile_fail` doctest on `WellFormed`; text verbatim, wrapping tidied.
const NEVER_KEYS_DIAG: &str = r#": this Noise pattern never keys the cipher: it performs no DH
              (ee/es/se/ss) and no psk token, so it provides no confidentiality
              or authentication
 --> src/main.rs:3:9
  |
3 |     pub Bad<X25519, ChaChaPoly, Blake2b> {
  |         ^^^ pattern finalises with an unkeyed cipher"#;

#[component]
pub fn App() -> impl IntoView {
    let wizard_open = RwSignal::new(false);
    // The invite button, so the wizard can hand keyboard focus back on close.
    let invite_btn = NodeRef::<html::Button>::new();
    view! {
        // `inert` while the wizard is open: the page behind the modal stops
        // being focusable or clickable, which is the whole focus trap.
        <main
            class="flex min-h-dvh flex-col px-5 md:px-10"
            inert=move || wizard_open.get().then_some("")
        >
            <Nav />
            <div class="mx-auto flex w-full max-w-6xl flex-1 flex-col justify-center gap-12 py-12 lg:flex-row lg:items-center lg:gap-20">
                <Hero />
                <Invite open=wizard_open btn=invite_btn />
            </div>
            <div class="mx-auto w-full max-w-6xl pb-6">
                <div class="static-band mb-6"></div>
                <ProofStrip />
                <PageFooter />
            </div>
        </main>
        <Wizard open=wizard_open invite_btn=invite_btn />
    }
}

#[component]
fn Nav() -> impl IntoView {
    view! {
        <nav class="flex items-baseline gap-5 border-b border-line-soft py-5 text-[13px]">
            <span class="text-[15px] font-semibold text-silver-bright">"hiss"</span>
            <a class="ml-auto text-silver-dim hover:text-cyan" href="https://docs.rs/hiss">
                "docs.rs ↗"
            </a>
            <a class="text-silver-dim hover:text-cyan" href=REPO>
                "github ↗"
            </a>
        </nav>
    }
}

#[component]
fn Hero() -> impl IntoView {
    view! {
        <header class="text-center lg:flex-1 lg:text-left">
            <p class="mb-5 text-[clamp(11px,0.75vw,13px)] uppercase tracking-[0.16em] text-silver-dim">
                "noise protocol framework · rust · sans-io · no async runtime"
            </p>
            <h1 class="mx-auto max-w-[20ch] text-[clamp(30px,3.4vw,58px)] font-semibold leading-[1.12] tracking-tight text-silver-bright [text-wrap:balance] lg:mx-0">
                "Encrypted, authenticated channels between two peers you control."
            </h1>
            <p class="mx-auto mt-5 max-w-[46ch] text-[clamp(15px,1.1vw,18px)] leading-relaxed text-silver-dim lg:mx-0">
                "You decide who proves themselves — the handshake enforces it, the compiler checks it."
            </p>
            <span class="mt-6 inline-block rounded-full border border-warn/50 px-3 py-1 text-xs text-warn">
                "unaudited · pre-1.0 — use at your own risk"
            </span>
            <div class="mt-7 flex flex-wrap items-center justify-center gap-3.5 lg:justify-start">
                <a
                    class="rounded-sm border border-line px-4 py-2 text-[13px] text-silver-dim hover:border-silver-faint hover:text-silver"
                    href="https://docs.rs/hiss"
                >
                    "read the quickstart →"
                </a>
                <span class="rounded-sm border border-line-soft bg-panel px-4 py-2 text-[13px]">
                    <span class="text-silver-faint">"$ "</span>
                    "cargo add hiss"
                </span>
            </div>
        </header>
    }
}

/// The one big call to action on the splash — the resolve motif above it:
/// static enters, signal leaves.
#[component]
fn Invite(open: RwSignal<bool>, btn: NodeRef<html::Button>) -> impl IntoView {
    view! {
        <section class="flex flex-col items-center text-center lg:w-[400px] lg:shrink-0">
            <svg
                viewBox="0 0 260 44"
                class="mb-8 w-56 md:w-64"
                aria-hidden="true"
            >
                <g stroke="#5a6068" stroke-width="1.5" stroke-linecap="round" opacity="0.6">
                    <line x1="6" y1="15" x2="6" y2="29"></line>
                    <line x1="14" y1="10" x2="14" y2="34"></line>
                    <line x1="22" y1="17" x2="22" y2="27"></line>
                    <line x1="30" y1="12" x2="30" y2="32"></line>
                    <line x1="38" y1="8" x2="38" y2="36"></line>
                    <line x1="46" y1="16" x2="46" y2="28"></line>
                    <line x1="54" y1="11" x2="54" y2="33"></line>
                    <line x1="62" y1="18" x2="62" y2="26"></line>
                    <line x1="70" y1="13" x2="70" y2="31"></line>
                    <line x1="78" y1="9" x2="78" y2="35"></line>
                    <line x1="86" y1="15" x2="86" y2="29"></line>
                    <line x1="94" y1="12" x2="94" y2="32"></line>
                </g>
                <path
                    d="M112 22 q 15 -26 30 0 t 30 0 t 30 0 t 30 0 t 24 0"
                    fill="none"
                    stroke="#5bc8d6"
                    stroke-width="2.5"
                    stroke-linecap="round"
                ></path>
            </svg>
            <p class="text-[clamp(15px,1.1vw,17px)] text-silver-dim">
                "The way you handshake decides who is authenticated."
            </p>
            <button
                node_ref=btn
                class="mt-7 cursor-pointer rounded-sm border-2 border-cyan-dim px-12 py-5 text-[clamp(16px,1.2vw,19px)] font-semibold text-cyan transition-colors hover:border-cyan hover:bg-cyan/10"
                on:click=move |_| open.set(true)
            >
                "find your handshake →"
            </button>
            <p class="mt-5 max-w-[38ch] text-xs leading-5 text-silver-faint">
                "three questions · a pattern, its properties, the code · real bytes, pinned by test"
            </p>
        </section>
    }
}

#[derive(Clone, Copy, PartialEq)]
enum Stage {
    AuthYou,
    AuthPeer,
    KnownKey,
    Result,
}

/// The modal wizard: three questions → a pattern, explained.
#[component]
fn Wizard(open: RwSignal<bool>, invite_btn: NodeRef<html::Button>) -> impl IntoView {
    let stage = RwSignal::new(Stage::AuthYou);
    let you = RwSignal::new(true);
    let peer = RwSignal::new(true);
    let known = RwSignal::new(false);
    // Which candidate the result card is showing — set to the recommendation
    // on every transition into `Stage::Result`, then driven by the tabs.
    let selected = RwSignal::new("XX");

    let panel_ref = NodeRef::<html::Div>::new();
    // Closing hands keyboard focus back to the invite button.
    let close = move || {
        open.set(false);
        if let Some(b) = invite_btn.get_untracked() {
            let _ = b.focus();
        }
    };

    // Opening always starts from the first question, with focus moved into
    // the dialog (the page behind it is `inert` meanwhile — see App).
    Effect::new(move |_| {
        if open.get() {
            stage.set(Stage::AuthYou);
            request_animation_frame(move || {
                if let Some(el) = panel_ref.get_untracked() {
                    let _ = el.focus();
                }
            });
        }
    });
    window_event_listener(ev::keydown, move |e| {
        if open.get_untracked() && e.key() == "Escape" {
            close();
        }
    });

    view! {
        <Show when=move || open.get()>
            <div
                class="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-ink/80 p-4 backdrop-blur-sm"
                role="dialog"
                aria-modal="true"
                aria-label="find your handshake"
                on:click=move |_| close()
            >
                <div
                    node_ref=panel_ref
                    tabindex="-1"
                    class="my-8 w-full max-w-2xl rounded-sm border border-line bg-panel p-6"
                    on:click=move |e| e.stop_propagation()
                >
                    <div class="flex items-baseline justify-between pb-4">
                        <span class="text-[13px] font-semibold text-silver-bright">
                            "find your handshake"
                        </span>
                        <button
                            class=GHOST_BTN
                            aria-label="close"
                            on:click=move |_| close()
                        >
                            "close ✕"
                        </button>
                    </div>
                    {move || match stage.get() {
                        Stage::AuthYou => {
                            view! {
                                <p class="text-xs text-silver-faint">"1 / 3"</p>
                                <h2 class="mt-1 text-lg font-semibold text-silver-bright">
                                    "Do you need to prove who you are?"
                                </h2>
                                <p class="mt-1 text-[13px] text-silver-dim">
                                    "You are the side opening the connection. If yes, your long-term key joins the handshake and the peer can pin or reject it."
                                </p>
                                <div class="mt-4 grid gap-3">
                                    <button
                                        class=ANSWER_CARD
                                        on:click=move |_| {
                                            you.set(true);
                                            stage.set(Stage::AuthPeer);
                                        }
                                    >
                                        <span class="text-[14px] text-silver-bright">
                                            "Yes — the peer must be able to verify me"
                                        </span>
                                        <span class="mt-1 block text-xs text-silver-dim">
                                            "enrolled devices, paired peers, anything with an identity"
                                        </span>
                                    </button>
                                    <button
                                        class=ANSWER_CARD
                                        on:click=move |_| {
                                            you.set(false);
                                            stage.set(Stage::AuthPeer);
                                        }
                                    >
                                        <span class="text-[14px] text-silver-bright">
                                            "No — I can stay anonymous"
                                        </span>
                                        <span class="mt-1 block text-xs text-silver-dim">
                                            "like a browser talking to a public server"
                                        </span>
                                    </button>
                                </div>
                            }
                                .into_any()
                        }
                        Stage::AuthPeer => {
                            view! {
                                <p class="text-xs text-silver-faint">"2 / 3"</p>
                                <h2 class="mt-1 text-lg font-semibold text-silver-bright">
                                    "Does the peer need to prove who they are?"
                                </h2>
                                <p class="mt-1 text-[13px] text-silver-dim">
                                    "The side answering. If yes, completing the handshake proves they hold a static key — and your code decides whether it is one you trust."
                                </p>
                                <div class="mt-4 grid gap-3">
                                    <button
                                        class=ANSWER_CARD
                                        on:click=move |_| {
                                            peer.set(true);
                                            stage.set(Stage::KnownKey);
                                        }
                                    >
                                        <span class="text-[14px] text-silver-bright">
                                            "Yes — I must know who I'm talking to"
                                        </span>
                                        <span class="mt-1 block text-xs text-silver-dim">
                                            "almost always what you want"
                                        </span>
                                    </button>
                                    <button
                                        class=ANSWER_CARD
                                        on:click=move |_| {
                                            peer.set(false);
                                            known.set(false);
                                            selected
                                                .set(fixtures::pick(you.get_untracked(), false, false));
                                            stage.set(Stage::Result);
                                        }
                                    >
                                        <span class="text-[14px] text-silver-bright">
                                            "No — any peer will do"
                                        </span>
                                        <span class="mt-1 block text-xs text-silver-dim">
                                            "rare: only sound with authentication layered on top"
                                        </span>
                                    </button>
                                </div>
                                <button
                                    class=GHOST_BTN
                                    style="margin-top: 1rem;"
                                    on:click=move |_| stage.set(Stage::AuthYou)
                                >
                                    "← back"
                                </button>
                            }
                                .into_any()
                        }
                        Stage::KnownKey => {
                            view! {
                                <p class="text-xs text-silver-faint">"3 / 3"</p>
                                <h2 class="mt-1 text-lg font-semibold text-silver-bright">
                                    "Do you already hold the peer's public key?"
                                </h2>
                                <p class="mt-1 text-[13px] text-silver-dim">
                                    "Shipped with your app, exchanged at enrolment, printed on the box — 32 bytes you trust before the first connection."
                                </p>
                                <div class="mt-4 grid gap-3">
                                    <button
                                        class=ANSWER_CARD
                                        on:click=move |_| {
                                            known.set(true);
                                            selected
                                                .set(fixtures::pick(you.get_untracked(), true, true));
                                            stage.set(Stage::Result);
                                        }
                                    >
                                        <span class="text-[14px] text-silver-bright">
                                            "Yes — I can know it in advance"
                                        </span>
                                        <span class="mt-1 block text-xs text-silver-dim">
                                            "fewer messages, and their key never rides the wire"
                                        </span>
                                    </button>
                                    <button
                                        class=ANSWER_CARD
                                        on:click=move |_| {
                                            known.set(false);
                                            selected
                                                .set(fixtures::pick(you.get_untracked(), true, false));
                                            stage.set(Stage::Result);
                                        }
                                    >
                                        <span class="text-[14px] text-silver-bright">
                                            "No — we meet cold"
                                        </span>
                                        <span class="mt-1 block text-xs text-silver-dim">
                                            "their key arrives during the handshake; your code verifies it"
                                        </span>
                                    </button>
                                </div>
                                <button
                                    class=GHOST_BTN
                                    style="margin-top: 1rem;"
                                    on:click=move |_| stage.set(Stage::AuthPeer)
                                >
                                    "← back"
                                </button>
                            }
                                .into_any()
                        }
                        Stage::Result => {
                            let recommended = fixtures::pick(you.get(), peer.get(), known.get());
                            let rec_inf = fixtures::info(recommended);
                            let sel = selected.get();
                            let inf = fixtures::info(sel);
                            let f = fixtures::fixture(sel);
                            let context = (sel != recommended)
                                .then(|| {
                                    rec_inf.alternates.iter().find(|a| a.name == sel).map(|a| a.note)
                                })
                                .flatten();
                            let tabs = std::iter::once(recommended)
                                .chain(rec_inf.alternates.iter().map(|a| a.name))
                                .map(|nm| {
                                    let cls = if nm == sel { TAB_ON } else { TAB_OFF };
                                    let label = if nm == recommended {
                                        format!("{nm} ★ recommended")
                                    } else {
                                        nm.to_string()
                                    };
                                    view! {
                                        <button class=cls on:click=move |_| selected.set(nm)>
                                            {label}
                                        </button>
                                    }
                                })
                                .collect_view();
                            view! {
                                <p class="text-xs text-silver-faint">
                                    "your handshake — and the ones that also fit"
                                </p>
                                <div class="mt-2 flex flex-wrap gap-2">{tabs}</div>
                                <h2 class="mt-4 text-2xl font-semibold tracking-tight">
                                    <span class="text-cyan">{sel}</span>
                                    <span class="text-sm text-silver-dim">
                                        {format!("  · {} messages", f.msgs.len())}
                                    </span>
                                    {(sel == "XX")
                                        .then(|| {
                                            view! {
                                                <span class="text-sm text-silver-faint">
                                                    "  · the default"
                                                </span>
                                            }
                                        })}
                                </h2>
                                {context
                                    .map(|c| {
                                        view! {
                                            <p class="mt-1 text-xs text-silver-dim">
                                                {format!("vs {recommended}: {c}")}
                                            </p>
                                        }
                                    })}
                                {inf
                                    .warn_note
                                    .map(|w| {
                                        view! {
                                            <p class="mt-3 rounded-sm border border-warn/50 bg-warn/5 p-3 text-xs leading-5 text-warn">
                                                {format!("⚠ {w}")}
                                            </p>
                                        }
                                    })}
                                {(sel == "NN")
                                    .then(|| {
                                        view! {
                                            <div class="mt-3">
                                                <p class="text-xs text-silver-dim">
                                                    "One step further — a pattern with no key exchange at all — and hiss refuses to compile it:"
                                                </p>
                                                <pre class="mt-2 overflow-x-auto rounded-sm border border-line-soft bg-ink p-3 text-[11px] leading-5 text-silver-dim">
                                                    <code>
                                                        <span class="text-blocked">"error[E0277]"</span>
                                                        {NEVER_KEYS_DIAG}
                                                    </code>
                                                </pre>
                                                <p class="mt-1 text-[10.5px] text-silver-faint">
                                                    "rustc's diagnostic — pinned by a compile_fail doctest in hiss (text verbatim, wrapping tidied)"
                                                </p>
                                            </div>
                                        }
                                    })}
                                <ul class="mt-4 space-y-1.5 text-[13px] text-silver-dim">
                                    {inf
                                        .why
                                        .iter()
                                        .map(|w| {
                                            view! {
                                                <li>
                                                    <span class="text-cyan">"– "</span>
                                                    {*w}
                                                </li>
                                            }
                                        })
                                        .collect_view()}
                                </ul>
                                <pre class="mt-4 overflow-x-auto rounded-sm border border-line-soft bg-ink p-3 text-xs leading-6 text-silver-dim">
                                    <code>
                                        <span class="text-cyan">"hiss::noise!"</span>
                                        {inf.decl}
                                    </code>
                                </pre>
                                <TracePanes name=sel />
                                <p class="mt-4 text-xs text-silver-dim">
                                    "Suite: "
                                    <span class="text-silver">"X25519 · ChaChaPoly · Blake2b"</span>
                                    " — the quickstart default. Keys living in an Apple Secure Enclave? Use "
                                    <span class="text-silver">"P256"</span>
                                    " — the only curve the enclave speaks."
                                </p>
                                <div class="mt-5 flex flex-wrap items-center gap-4 border-t border-line-soft pt-4 text-xs">
                                    <a
                                        class="cursor-pointer rounded-sm border border-cyan-dim px-4 py-2 text-[13px] text-cyan hover:border-cyan hover:bg-cyan/10"
                                        href="https://docs.rs/hiss"
                                    >
                                        "read the quickstart →"
                                    </a>
                                    <a class="text-silver-dim hover:text-cyan" href=inf.explorer>
                                        "formal analysis ↗"
                                    </a>
                                    <button
                                        class=GHOST_BTN
                                        on:click=move |_| stage.set(Stage::AuthYou)
                                    >
                                        "start over ↺"
                                    </button>
                                </div>
                            }
                                .into_any()
                        }
                    }}
                </div>
            </div>
        </Show>
    }
}

/// A trace row that becomes visible once the sequencer passes step `k`.
#[component]
fn Reveal(k: usize, step: RwSignal<usize>, children: Children) -> impl IntoView {
    let shown = move || step.get() > k;
    let class = move || {
        if shown() {
            "trace-row opacity-100 transition-opacity duration-500"
        } else {
            "trace-row opacity-0 transition-opacity duration-500"
        }
    };
    view! { <div class=class>{children()}</div> }
}

/// The pattern's frozen trace, replayed: real messages between "you" and
/// "peer", the channel opening, and a sealed ping/pong. Autoplays on mount.
#[component]
fn TracePanes(name: &'static str) -> impl IntoView {
    let step = RwSignal::new(0usize);
    let replay = RwSignal::new(0usize);
    let handles: StoredValue<Vec<TimeoutHandle>> = StoredValue::new(Vec::new());

    Effect::new(move |_| {
        replay.track();
        handles.update_value(|v| {
            for h in v.drain(..) {
                h.clear();
            }
        });
        step.set(0);
        let total = fixtures::fixture(name).msgs.len() + 3;
        for i in 1..=total {
            let delay = Duration::from_millis(350 + 550 * i as u64);
            let cb = move || {
                let _ = step.try_update(|s| *s = (*s).max(i));
            };
            if let Ok(h) = set_timeout_with_handle(cb, delay) {
                handles.update_value(|v| v.push(h));
            }
        }
    });
    on_cleanup(move || {
        let _ = handles.try_update_value(|v| {
            for h in v.drain(..) {
                h.clear();
            }
        });
    });

    let f = fixtures::fixture(name);
    let last = f.msgs.len();

    let mut you_rows: Vec<AnyView> = Vec::new();
    let mut peer_rows: Vec<AnyView> = Vec::new();
    if let Some(pre) = f.pre {
        you_rows.push(
            view! {
                <div class="text-silver-faint">
                    {format!("{pre}   · peer's key, known in advance")}
                </div>
            }
            .into_any(),
        );
    }
    for (i, m) in f.msgs.iter().enumerate() {
        let (arrow, rows) = match m.dir {
            Dir::ToPeer => ("→ ", &mut you_rows),
            Dir::FromPeer => ("← ", &mut peer_rows),
        };
        rows.push(
            view! {
                <Reveal k=i step=step>
                    <span class="text-cyan">{arrow}{m.tokens}</span>
                    <span class="text-silver-faint">{format!("  · {} B", m.size)}</span>
                    <div class="text-[10px] text-silver-faint">{m.preview}</div>
                </Reveal>
            }
            .into_any(),
        );
    }
    you_rows.push(
        view! {
            <Reveal k=last step=step>
                <span class="text-cyan">"✓ channel open"</span>
                <div class="text-[10px] text-silver-faint">{format!("session {}", f.session)}</div>
            </Reveal>
        }
        .into_any(),
    );
    peer_rows.push(
        view! {
            <Reveal k=last step=step>
                <span class="text-cyan">"✓ channel open"</span>
            </Reveal>
        }
        .into_any(),
    );
    you_rows.push(
        view! {
            <Reveal k={last + 1} step=step>
                <span class="text-silver">"→ \"ping\", sealed"</span>
                <span class="text-silver-faint">{format!("  · {} B tag", f.overhead)}</span>
                <div class="text-[10px] text-silver-faint">{f.ping_ct}</div>
            </Reveal>
        }
        .into_any(),
    );
    peer_rows.push(
        view! {
            <Reveal k={last + 2} step=step>
                <span class="text-silver">"« ping » · ← \"pong\", sealed"</span>
                <div class="text-[10px] text-silver-faint">{f.pong_ct}</div>
            </Reveal>
        }
        .into_any(),
    );

    view! {
        <div class="mt-4">
            <div class="flex items-baseline justify-between pb-1">
                <span class="text-[10.5px] uppercase tracking-[0.14em] text-silver-faint">
                    "watch it run"
                </span>
                <button
                    class=GHOST_BTN
                    aria-label="replay the handshake"
                    on:click=move |_| replay.update(|r| *r += 1)
                >
                    "replay ⟳"
                </button>
            </div>
            <div class="grid gap-3 md:grid-cols-2">
                <div class="min-h-32 rounded-sm border border-line-soft bg-ink p-3 text-xs leading-6">
                    <div class="pb-1 font-semibold text-silver-bright">"you"</div>
                    {you_rows}
                </div>
                <div class="min-h-32 rounded-sm border border-line-soft bg-ink p-3 text-xs leading-6">
                    <div class="pb-1 font-semibold text-silver-bright">"peer"</div>
                    {peer_rows}
                </div>
            </div>
            <p class="pt-1.5 text-[10.5px] text-silver-faint">
                "real bytes — "
                <a class="hover:text-cyan" href=PINNED>
                    "generated by hiss, pinned by test"
                </a>
            </p>
        </div>
    }
}

#[component]
fn ProofStrip() -> impl IntoView {
    view! {
        <section id="proof" class="flex flex-wrap items-baseline gap-x-2 gap-y-1.5 text-xs">
            <a class="text-silver-dim hover:text-cyan" href=TESTED>
                "17-pattern KATs ✓"
            </a>
            <span class="text-silver-faint">"·"</span>
            <a class="text-silver-dim hover:text-cyan" href=TESTED>
                "Wycheproof 484 + 355 ✓"
            </a>
            <span class="text-silver-faint">"·"</span>
            <a class="text-silver-dim hover:text-cyan" href=TESTED>
                "snow interop ✓"
            </a>
            <span class="text-silver-faint">"·"</span>
            <a class="text-silver-dim hover:text-cyan" href=TESTED>
                "cacophony vectors ✓"
            </a>
            <span class="text-silver-faint">"·"</span>
            <a class="text-warn" href="https://github.com/primetype/hiss#security">
                "unaudited · pre-1.0"
            </a>
            <span class="text-silver-faint">"·"</span>
            <a class="text-silver-dim hover:text-cyan" href="https://noiseexplorer.com/patterns/">
                "formal pattern analyses ↗"
            </a>
        </section>
    }
}

#[component]
fn PageFooter() -> impl IntoView {
    view! {
        <footer class="mt-5 border-t border-line-soft pt-5 text-xs leading-6 text-silver-faint">
            <p class="mb-3">
                "0.2 is unreleased — the 0.1.0 on crates.io predates the "
                <span class="text-silver-dim">"noise!"</span>
                " macro this page describes."
            </p>
            <div class="mb-3 flex flex-wrap gap-x-5 gap-y-1">
                <a class="text-silver-dim hover:text-cyan" href="https://docs.rs/hiss">
                    "docs.rs"
                </a>
                <a class="text-silver-dim hover:text-cyan" href="https://crates.io/crates/hiss">
                    "crates.io"
                </a>
                <a class="text-silver-dim hover:text-cyan" href=REPO>
                    "github"
                </a>
                <a class="text-silver-dim hover:text-cyan" href="https://crates.io/crates/snow">
                    "need more Noise? snow ↗"
                </a>
            </div>
            <p>
                "Apache-2.0 OR MIT · built on the "
                <a class="text-silver-dim hover:text-cyan" href="https://noiseprotocol.org/">
                    "Noise Protocol Framework"
                </a>
                " · report security issues privately to the maintainers, not as public issues."
            </p>
        </footer>
    }
}
