//! The hiss one-page site.
//!
//! A pure client-side (CSR) Leptos app, deployed to GitHub Pages. The
//! centerpiece is the handshake device ([`app::Device`]): three toggles
//! resolve to a real Noise pattern whose frozen trace — bytes generated by
//! hiss, pinned by `tests/fixtures.rs` — replays in the page. The shipped
//! WASM never links hiss; see [`fixtures`].

mod app;
mod fixtures;

fn main() {
    // Surface Rust panics in the browser console with a readable backtrace.
    console_error_panic_hook::set_once();
    leptos::mount::mount_to_body(app::App);
}
