//! Noise handshake state machine.
//!
//! The three state types — [`HandshakeState`], [`Sending`], and
//! [`Receiving`] — form a type-state machine driven by the Cons-list
//! token sequence from the [`Pattern`] trait.
//!
//! * [`HandshakeState`] sits *between* messages. Its only operations
//!   are starting the next send or receive message, or finishing the
//!   handshake when all messages have been processed.
//!
//! * [`Sending`] and [`Receiving`] sit *within* a message. Each
//!   token method (`.e()`, `.es()`, etc.) advances the token
//!   Cons-list by one step. The return type changes depending on
//!   whether more tokens remain, more messages remain, or the
//!   handshake is complete.

use super::Protocol;
use super::buffers::{RecvBuffer, SendBuffer};
use super::cipher::Cipher;
use super::error::HandshakeError;
use super::hash::Hash;
use super::pattern::Pattern;
use super::role::{Initiator, Responder, Role};
use super::symmetric_state::SymmetricState;
use super::tokens::*;
use crate::curve::Curve;
use crate::provider::{CryptoKeys, CryptoProviderAsync};
use std::marker::PhantomData;

// ── Wire size helper ─────────────────────────────────────────

/// Select the correct compile-time wire size constant based on the
/// runtime keyed state and the pattern's PSK modifier.
///
/// All four values (`SIZE_KEYED`/`SIZE_UNKEYED` × `HAS_PSK`
/// true/false) are compile-time constants. The two runtime booleans
/// (`has_psk`, `has_key`) select which one applies.
///
/// The Noise spec requires `EncryptAndHash(payload)` after all
/// tokens in each message. With an empty payload and a keyed cipher
/// state, this produces `TAG_SIZE` additional bytes (the
/// authentication tag). The `keyed_at_end` flag tracks whether the
/// cipher state is keyed after processing all tokens.
fn wire_size<Cu, Ci, Tokens>(has_psk: bool, has_key: bool) -> usize
where
    Cu: Curve,
    Ci: Cipher,
    Tokens: WireSize<Cu, Ci, true> + WireSize<Cu, Ci, false>,
{
    let (token_size, keyed_at_end) = if has_psk {
        if has_key {
            (
                <Tokens as WireSize<Cu, Ci, true>>::SIZE_KEYED,
                <Tokens as WireSize<Cu, Ci, true>>::KEYED_AFTER_KEYED,
            )
        } else {
            (
                <Tokens as WireSize<Cu, Ci, true>>::SIZE_UNKEYED,
                <Tokens as WireSize<Cu, Ci, true>>::KEYED_AFTER_UNKEYED,
            )
        }
    } else if has_key {
        (
            <Tokens as WireSize<Cu, Ci, false>>::SIZE_KEYED,
            <Tokens as WireSize<Cu, Ci, false>>::KEYED_AFTER_KEYED,
        )
    } else {
        (
            <Tokens as WireSize<Cu, Ci, false>>::SIZE_UNKEYED,
            <Tokens as WireSize<Cu, Ci, false>>::KEYED_AFTER_UNKEYED,
        )
    };

    let payload_tag = if keyed_at_end { Ci::TAG_SIZE } else { 0 };
    token_size + payload_tag
}

// ── Runtime state shared across all type states ───────────────

/// The runtime handshake data, threaded through every type state.
///
/// Separated from the type-state wrappers so that token methods can
/// operate on it without fighting ownership.
pub(crate) struct HandshakeInner<Cu, Ci, H, CP>
where
    Cu: Curve,
    Ci: Cipher,
    H: Hash,
    CP: CryptoKeys<Cu>,
{
    pub(crate) symmetric: SymmetricState<Ci, H>,
    /// Our ephemeral private key (generated by the `E` token).
    pub(crate) e: Option<CP::PrivateKey>,
    /// Our ephemeral public key (derived from `e` during the `E` token).
    pub(crate) e_pub: Option<Cu::PublicKey>,
    /// Our static private key (provided by the `S` token).
    pub(crate) s: Option<CP::PrivateKey>,
    /// Our static public key (derived from `s`).
    pub(crate) s_pub: Option<Cu::PublicKey>,
    /// Remote party's ephemeral public key (received via `E` token).
    pub(crate) re: Option<Cu::PublicKey>,
    /// Remote party's static public key.
    pub(crate) rs: Option<Cu::PublicKey>,
    /// Whether the pattern includes a PSK modifier (affects `E` token
    /// behaviour — it additionally calls `mix_key` on the ephemeral
    /// public key).
    pub(crate) has_psk: bool,
    /// The crypto provider (key generation, DH, signing).
    pub(crate) provider: CP,
}

// ── HandshakeState — between messages ─────────────────────────

/// The handshake state between messages.
///
/// Type parameters:
/// * `N` — the protocol descriptor (e.g.
///   `IKpsk1`)
/// * `R` — role ([`Initiator`] or
///   [`Responder`])
/// * `PreMsgs` — remaining pre-message Cons-list. Starts as
///   [`Pattern::PreMessages`] and advances toward [`Nil`] as
///   pre-message keys are provided via `set_s` / `set_rs`.
///   Handshake messages can only be processed once this reaches
///   [`Nil`].
/// * `Msgs` — the remaining handshake message Cons-list
/// * `CP` — the [`CryptoProviderAsync`] implementation
pub struct HandshakeState<N, R, Stage, Msgs, CP>
where
    N: Protocol,
    CP: CryptoKeys<N::Curve>,
{
    pub(crate) inner: HandshakeInner<N::Curve, N::Cipher, N::Hash, CP>,
    pub(crate) _marker: PhantomData<fn() -> (N, R, Stage, Msgs)>,
}

// ── Construction ──────────────────────────────────────────────

impl<N, R, CP>
    HandshakeState<
        N,
        R,
        <N::Pattern as Pattern>::PreMessages,
        <N::Pattern as Pattern>::Messages,
        CP,
    >
where
    N: Protocol,
    R: Role,
    CP: CryptoKeys<N::Curve>,
{
    /// Begin a new handshake for the given protocol and role.
    ///
    /// The protocol descriptor `N` (e.g.
    /// `IKpsk1`) determines the
    /// pattern, curve, cipher, and hash. The pre-message Cons-list
    /// from the pattern becomes the `PreMsgs` type parameter —
    /// pre-message keys must be provided (via `set_s` or
    /// `set_rs`) to advance it to [`Nil`] before the handshake
    /// can proceed.
    ///
    /// The `prologue` is mixed into the handshake hash before any
    /// tokens are processed. Both sides must use the same prologue
    /// for the handshake to succeed. Use this to bind protocol
    /// version, negotiation parameters, or other context into the
    /// session.
    ///
    /// # Example
    ///
    /// ```ignore
    /// type Channel = IKpsk1;
    ///
    /// let hs = HandshakeState::<Channel, Initiator, _, _, _>::new(provider, &[])
    ///     .set_rs(responder_pub);
    /// ```
    pub fn new(provider: CP, prologue: &[u8]) -> Self {
        let protocol_name = format!(
            "Noise_{}_{}_{}_{}",
            <N::Pattern as Pattern>::NAME,
            <N::Curve as Curve>::NAME,
            <N::Cipher as Cipher>::NAME,
            <N::Hash as Hash>::NAME,
        );
        let mut symmetric = SymmetricState::<N::Cipher, N::Hash>::initialize(&protocol_name);

        // Noise spec §5.3: MixHash(prologue).
        symmetric.mix_hash(prologue);

        HandshakeState {
            inner: HandshakeInner {
                symmetric,
                e: None,
                e_pub: None,
                s: None,
                s_pub: None,
                re: None,
                rs: None,
                has_psk: <N::Pattern as Pattern>::HAS_PSK,
                provider,
            },
            _marker: PhantomData,
        }
    }
}

// ── Pre-message processing ───────────────────────────────────
//
// The Stage type parameter carries the pattern's PreMessages
// Cons-list. Each `set_s()` / `set_rs()` call consumes one
// pre-message Message and advances the list. The direction
// (`ToInitiator` / `ToResponder`) combined with the role
// determines which method is available — the compiler rejects
// the wrong one.

// `<- s` (ToInitiator) + Initiator: the responder's static key
// is known to us as the remote static → set_rs.
impl<N, Tokens, Rest, Msgs, CP>
    HandshakeState<N, Initiator, Cons<Message<ToInitiator, Tokens>, Rest>, Msgs, CP>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Provide the remote party's static public key for the
    /// `<- s` pre-message.
    ///
    /// Only available to the **initiator** — the `<- s` direction
    /// means the responder's static key is known to us as the
    /// remote static.
    pub fn set_rs(
        mut self,
        remote_static: <N::Curve as Curve>::PublicKey,
    ) -> HandshakeState<N, Initiator, Rest, Msgs, CP> {
        self.inner.symmetric.mix_hash(remote_static.as_ref());
        self.inner.rs = Some(remote_static);
        HandshakeState {
            inner: self.inner,
            _marker: PhantomData,
        }
    }
}

// `<- s` (ToInitiator) + Responder: this is our own static key
// → set_s.
impl<N, Tokens, Rest, Msgs, CP>
    HandshakeState<N, Responder, Cons<Message<ToInitiator, Tokens>, Rest>, Msgs, CP>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Provide our local static key for the `<- s` pre-message.
    ///
    /// Only available to the **responder** — the `<- s` direction
    /// means our own static key is known to the initiator.
    pub fn set_s(
        mut self,
        static_key: CP::PrivateKey,
    ) -> Result<HandshakeState<N, Responder, Rest, Msgs, CP>, HandshakeError> {
        let s_pub = self
            .inner
            .provider
            .public_key(&static_key)
            .map_err(|e| HandshakeError::Crypto(Box::new(e)))?;
        self.inner.symmetric.mix_hash(s_pub.as_ref());
        self.inner.s_pub = Some(s_pub);
        self.inner.s = Some(static_key);
        Ok(HandshakeState {
            inner: self.inner,
            _marker: PhantomData,
        })
    }
}

// `-> s` (ToResponder) + Initiator: this is our own static key
// → set_s.
impl<N, Tokens, Rest, Msgs, CP>
    HandshakeState<N, Initiator, Cons<Message<ToResponder, Tokens>, Rest>, Msgs, CP>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Provide our local static key for the `-> s` pre-message.
    ///
    /// Only available to the **initiator** — the `-> s` direction
    /// means our own static key is known to the responder.
    pub fn set_s(
        mut self,
        static_key: CP::PrivateKey,
    ) -> Result<HandshakeState<N, Initiator, Rest, Msgs, CP>, HandshakeError> {
        let s_pub = self
            .inner
            .provider
            .public_key(&static_key)
            .map_err(|e| HandshakeError::Crypto(Box::new(e)))?;
        self.inner.symmetric.mix_hash(s_pub.as_ref());
        self.inner.s_pub = Some(s_pub);
        self.inner.s = Some(static_key);
        Ok(HandshakeState {
            inner: self.inner,
            _marker: PhantomData,
        })
    }
}

// `-> s` (ToResponder) + Responder: the initiator's static key
// is known to us as the remote static → set_rs.
impl<N, Tokens, Rest, Msgs, CP>
    HandshakeState<N, Responder, Cons<Message<ToResponder, Tokens>, Rest>, Msgs, CP>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Provide the remote party's static public key for the
    /// `-> s` pre-message.
    ///
    /// Only available to the **responder** — the `-> s` direction
    /// means the initiator's static key is known to us as the
    /// remote static.
    pub fn set_rs(
        mut self,
        remote_static: <N::Curve as Curve>::PublicKey,
    ) -> HandshakeState<N, Responder, Rest, Msgs, CP> {
        self.inner.symmetric.mix_hash(remote_static.as_ref());
        self.inner.rs = Some(remote_static);
        HandshakeState {
            inner: self.inner,
            _marker: PhantomData,
        }
    }
}

// ── Transitions: HandshakeState → Sending / Receiving ─────────

// Start a send message (when next message direction = our SendDir).
// Only available once all pre-messages have been processed (PreMsgs = Nil).
impl<N, R, Dir, Tokens, Rest, CP> HandshakeState<N, R, Nil, Cons<Message<Dir, Tokens>, Rest>, CP>
where
    N: Protocol,
    R: Role<SendDir = Dir>,
    CP: CryptoProviderAsync<N::Curve>,
    Tokens: WireSize<N::Curve, N::Cipher, true> + WireSize<N::Curve, N::Cipher, false>,
{
    /// Begin sending the next handshake message into the provided
    /// output buffer.
    ///
    /// The buffer must be exactly the right size for this message.
    /// Use [`noise_message_size!`](crate::noise_message_size) to compute the size at compile
    /// time, or [`expected_send_size`](Self::expected_send_size) to query it at runtime.
    ///
    /// This is called implicitly by the first token method — users
    /// do not need to call this directly. It transitions from
    /// [`HandshakeState`] to [`Sending`].
    pub(crate) fn begin_send(self, output: &mut [u8]) -> Sending<'_, N, R, Tokens, Rest, CP> {
        Sending {
            inner: self.inner,
            buffer: SendBuffer::new(output),
            _marker: PhantomData,
        }
    }

    /// Returns the exact number of bytes needed for the next
    /// outgoing message.
    pub fn expected_send_size(&self) -> usize {
        wire_size::<N::Curve, N::Cipher, Tokens>(self.inner.has_psk, self.inner.symmetric.has_key())
    }
}

// Start a receive message (when next message direction = our RecvDir).
// Only available once all pre-messages have been processed (PreMsgs = Nil).
impl<N, R, Dir, Tokens, Rest, CP> HandshakeState<N, R, Nil, Cons<Message<Dir, Tokens>, Rest>, CP>
where
    N: Protocol,
    R: Role<RecvDir = Dir>,
    CP: CryptoProviderAsync<N::Curve>,
    Tokens: WireSize<N::Curve, N::Cipher, true> + WireSize<N::Curve, N::Cipher, false>,
{
    /// Begin reading an incoming handshake message.
    ///
    /// Borrows the incoming message directly — no copy. Validates
    /// that the message length matches the expected wire size.
    ///
    /// Returns [`HandshakeError::UnexpectedMessageLength`] if the
    /// message length does not match the expected size.
    pub fn read<'a>(
        self,
        message: &'a [u8],
    ) -> Result<Receiving<'a, N, R, Tokens, Rest, CP>, HandshakeError> {
        let expected = wire_size::<N::Curve, N::Cipher, Tokens>(
            self.inner.has_psk,
            self.inner.symmetric.has_key(),
        );
        if message.len() != expected {
            return Err(HandshakeError::UnexpectedMessageLength {
                expected,
                actual: message.len(),
            });
        }
        Ok(Receiving {
            inner: self.inner,
            buffer: RecvBuffer::new(message),
            _marker: PhantomData,
        })
    }

    /// Returns the exact number of bytes expected for the next
    /// incoming message, computed at compile time from the token list.
    pub fn expected_message_size(&self) -> usize {
        wire_size::<N::Curve, N::Cipher, Tokens>(self.inner.has_psk, self.inner.symmetric.has_key())
    }
}

// ── Sending — within a send message ───────────────────────────

/// State within a send message.
///
/// Each token method appends data to the borrowed output buffer and
/// advances the token Cons-list. The return type depends on the
/// remaining tokens and messages.
pub struct Sending<'a, N, R, Tokens, MsgRest, CP>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
{
    pub(crate) inner: HandshakeInner<N::Curve, N::Cipher, N::Hash, CP>,
    pub(crate) buffer: SendBuffer<'a>,
    pub(crate) _marker: PhantomData<fn() -> (N, R, Tokens, MsgRest)>,
}

// ── Receiving — within a receive message ──────────────────────

/// State within a receive message.
///
/// Each token method reads data from the borrowed input buffer and
/// advances the token Cons-list. The return type depends on the
/// remaining tokens and messages. No copy — the incoming message
/// bytes are read directly.
pub struct Receiving<'a, N, R, Tokens, MsgRest, CP>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
{
    pub(crate) inner: HandshakeInner<N::Curve, N::Cipher, N::Hash, CP>,
    pub(crate) buffer: RecvBuffer<'a>,
    pub(crate) _marker: PhantomData<fn() -> (N, R, Tokens, MsgRest)>,
}
