//! Asynchronous `tokio::io` handshake adapter (feature `async-io`).
//!
//! The async mirror of [`io_sync`](super::io_sync): a
//! [`tokio::io::AsyncRead`]/[`tokio::io::AsyncWrite`] surface over the
//! same type-state Noise handshake as the buffer core. The caller hands
//! the handshake a stream and drives it with a fluent token chain that
//! `.await`s reads/writes on the wire directly, with no caller-sized
//! buffer:
//!
//! ```ignore
//! use hiss::noise::*;
//! type Seal = Noise<N, P256, ChaChaPoly, Blake2b>;
//!
//! // initiator — `stream: impl tokio::io::AsyncWrite + Unpin`
//! let i = AsyncHandshake::<Seal, Initiator, _, _, _, _>::initiate(provider, &[], stream)
//!     .set_rs(recipient_pub);
//! let mut sealed = i.e().await?.es().await?;   // msg1 streamed + flushed; `sealed` owns the stream
//!
//! // responder — `stream: impl tokio::io::AsyncRead + Unpin`
//! let r = AsyncHandshake::<Seal, Responder, _, _, _, _>::respond(provider, &[], stream)
//!     .set_s(recipient_static)?;
//! let (their_e, recv) = r.recv().e().await?;   // each token reads exactly its bytes off the wire
//! let mut opened = recv.es().await?;
//! ```
//!
//! # Design
//!
//! This layer is **purely additive**: the buffer-based core
//! ([`HandshakeState`]/[`Sending`]/[`Receiving`](super::handshake)) is
//! untouched and remains canonical, and so is the blocking
//! [`io_sync`](super::io_sync) layer. Each token method here threads its
//! compile-time [`WireSize`](super::tokens::WireSize)-sized bytes through
//! a small fixed stack scratch and streams them to the stream, so the
//! bytes on the wire are identical to both other paths; only buffer
//! ownership and the I/O differ. The structure mirrors
//! [`io_sync`](super::io_sync): three `impl` blocks per token per context,
//! generated by macros.
//!
//! The per-token crypto is shared verbatim with the buffer core — the
//! `async` token helpers in [`process`](super::process) are reused
//! directly, so there is a single source of truth for the Noise mix
//! sequence.
//!
//! # Asynchronous crypto
//!
//! The handshake is generic over [`CryptoProviderAsync`] — the
//! async provider surface — and `.await`s its operations. Both backends
//! implement it: software (`eccoxide`) resolves immediately, and Apple
//! **Secure Enclave** offloads its blocking Security-framework calls to
//! a worker thread (`tokio::task::spawn_blocking`) so the executor never
//! blocks. A sync-only provider that does not implement
//! [`CryptoProviderAsync`] is a *compile* error here.
//!
//! # Flushing & cancellation
//!
//! Each completed outgoing handshake message is flushed before the call
//! returns, so it reaches the peer even over a buffered stream (the
//! `tokio-rustls` contract). Bytes are streamed per token and crypto
//! state advances as they are produced, so dropping a handshake future
//! mid-message — or a mid-handshake I/O error — is **fatal and
//! unrecoverable**: drop the whole handshake and the connection; there
//! is no per-token retry.

use std::marker::PhantomData;

use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt};

use super::Protocol;
use super::buffers::{RecvBuffer, SendBuffer};
use super::cipher::Cipher;
use super::error::HandshakeError;
use super::handshake::{HandshakeInner, HandshakeState};
use super::hash::Hash;
use super::pattern::Pattern;
use super::process::{
    do_ee, do_es_initiator, do_es_responder, do_psk, do_se_initiator, do_se_responder, do_ss,
    recv_e, recv_payload, recv_s, recv_to_transport, send_e, send_payload, send_s,
};
use super::role::{Initiator, Responder, Role};
use super::tokens::*;
use super::transport::Transport;
use crate::curve::{CryptoKeys, CryptoProviderAsync, Curve};

/// Largest single contiguous write/read a token produces: an encrypted
/// static key (`PUBLIC_KEY_SIZE + TAG_SIZE`). 128 bytes covers every
/// supported curve/cipher with margin; the payload tag uses far less.
const TOKEN_SCRATCH: usize = 128;

// ── Streaming token helpers (compute bytes → write/read the wire) ──
//
// The DH/ephemeral mix steps reuse `process.rs`'s async helpers verbatim
// (`send_e`/`do_ee`/`do_es_*`/`do_se_*`/`do_ss`); these wrappers add the
// owned-stream I/O around them.

/// `e` (send): generate + mix the ephemeral and stream its public key.
async fn async_stream_e<Cu, Ci, H, CP, Io>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    stream: &mut Io,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Cu::PublicKey: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoProviderAsync<Cu>,
    Io: AsyncWrite + Unpin,
{
    let mut scratch = [0u8; TOKEN_SCRATCH];
    let mut buffer = SendBuffer::new(&mut scratch);
    send_e(inner, &mut buffer).await?;
    stream.write_all(buffer.finish()).await?;
    Ok(())
}

/// `s` (send): encrypt + mix the static key and stream it.
async fn async_stream_s<Cu, Ci, H, CP, Io>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    stream: &mut Io,
    static_key: CP::PrivateKey,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Cu::PublicKey: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoKeys<Cu>,
    Io: AsyncWrite + Unpin,
{
    let mut scratch = [0u8; TOKEN_SCRATCH];
    let mut buffer = SendBuffer::new(&mut scratch);
    send_s(inner, &mut buffer, static_key)?;
    stream.write_all(buffer.finish()).await?;
    Ok(())
}

/// `e` (recv): read the remote ephemeral public key and mix it in.
async fn async_read_e<Cu, Ci, H, CP, Io>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    stream: &mut Io,
) -> Result<Cu::PublicKey, HandshakeError>
where
    Cu: Curve,
    Cu::PublicKey: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoKeys<Cu>,
    Io: AsyncRead + Unpin,
{
    let pk_size = Cu::PUBLIC_KEY_SIZE;
    let mut scratch = [0u8; TOKEN_SCRATCH];
    stream.read_exact(&mut scratch[..pk_size]).await?;
    let mut buffer = RecvBuffer::new(&scratch[..pk_size]);
    recv_e(inner, &mut buffer)
}

/// `s` (recv): read + decrypt the remote static key and mix it in.
async fn async_read_s<Cu, Ci, H, CP, Io>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    stream: &mut Io,
) -> Result<Cu::PublicKey, HandshakeError>
where
    Cu: Curve,
    Cu::PublicKey: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoKeys<Cu>,
    Io: AsyncRead + Unpin,
{
    let wire_len = if inner.symmetric.has_key() {
        Cu::PUBLIC_KEY_SIZE + Ci::TAG_SIZE
    } else {
        Cu::PUBLIC_KEY_SIZE
    };
    let mut scratch = [0u8; TOKEN_SCRATCH];
    stream.read_exact(&mut scratch[..wire_len]).await?;
    let mut buffer = RecvBuffer::new(&scratch[..wire_len]);
    recv_s(inner, &mut buffer)
}

/// Close an outgoing message: encrypt-and-hash the empty payload, stream
/// the resulting tag, and flush so a buffered stream releases the whole
/// message (and a multi-message handshake does not deadlock).
async fn send_message_tail_async<Cu, Ci, H, CP, Io>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    stream: &mut Io,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Ci: Cipher,
    H: Hash,
    CP: CryptoKeys<Cu>,
    Io: AsyncWrite + Unpin,
{
    let tag_len = if inner.symmetric.has_key() {
        Ci::TAG_SIZE
    } else {
        0
    };
    let mut scratch = [0u8; TOKEN_SCRATCH];
    let mut buffer = SendBuffer::new(&mut scratch[..tag_len]);
    send_payload(inner, &mut buffer)?;
    stream.write_all(buffer.finish()).await?;
    stream.flush().await?;
    Ok(())
}

/// Close an incoming message: read and verify the trailing empty-payload
/// tag (`TAG_SIZE` bytes when keyed, nothing otherwise).
async fn recv_message_tail_async<Cu, Ci, H, CP, Io>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    stream: &mut Io,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Ci: Cipher,
    H: Hash,
    CP: CryptoKeys<Cu>,
    Io: AsyncRead + Unpin,
{
    let tag_len = if inner.symmetric.has_key() {
        Ci::TAG_SIZE
    } else {
        0
    };
    let mut scratch = [0u8; TOKEN_SCRATCH];
    stream.read_exact(&mut scratch[..tag_len]).await?;
    let mut buffer = RecvBuffer::new(&scratch[..tag_len]);
    recv_payload(inner, &mut buffer)
}

// ═══════════════════════════════════════════════════════════════
//  State types — mirror the buffer core, but own the stream `Io`
//  instead of borrowing a buffer (so there is no `'a` lifetime).
// ═══════════════════════════════════════════════════════════════

/// Asynchronous handshake state between messages. See the module docs.
pub struct AsyncHandshake<N, R, Stage, Msgs, CP, Io>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
{
    inner: HandshakeInner<N::Curve, N::Cipher, N::Hash, CP>,
    stream: Io,
    _marker: PhantomData<fn() -> (N, R, Stage, Msgs)>,
}

/// Asynchronous state within an outgoing message.
pub struct AsyncSending<N, R, Tokens, MsgRest, CP, Io>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
{
    inner: HandshakeInner<N::Curve, N::Cipher, N::Hash, CP>,
    stream: Io,
    _marker: PhantomData<fn() -> (N, R, Tokens, MsgRest)>,
}

/// Asynchronous state within an incoming message.
pub struct AsyncReceiving<N, R, Tokens, MsgRest, CP, Io>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
{
    inner: HandshakeInner<N::Curve, N::Cipher, N::Hash, CP>,
    stream: Io,
    _marker: PhantomData<fn() -> (N, R, Tokens, MsgRest)>,
}

/// Completed handshake plus the stream it ran over.
///
/// Like a TLS stream, the post-handshake [`Transport`] and the `Io` it
/// rides on are bundled together; [`into_parts`](Self::into_parts)
/// recovers them separately.
pub struct AsyncTransport<N: Protocol, Io> {
    transport: Transport<N>,
    stream: Io,
}

impl<N: Protocol, Io> AsyncTransport<N, Io> {
    /// The post-handshake transport cipher pair.
    pub fn transport(&mut self) -> &mut Transport<N> {
        &mut self.transport
    }

    /// The underlying stream.
    pub fn stream(&mut self) -> &mut Io {
        &mut self.stream
    }

    /// Split into the transport and the stream.
    pub fn into_parts(self) -> (Transport<N>, Io) {
        (self.transport, self.stream)
    }
}

// ═══════════════════════════════════════════════════════════════
//  Construction
// ═══════════════════════════════════════════════════════════════

impl<N, CP, Io>
    AsyncHandshake<
        N,
        Initiator,
        <N::Pattern as Pattern>::PreMessages,
        <N::Pattern as Pattern>::Messages,
        CP,
        Io,
    >
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
{
    /// Begin an async handshake as the **initiator** over `stream`.
    pub fn initiate(provider: CP, prologue: &[u8], stream: Io) -> Self {
        let core = HandshakeState::<
            N,
            Initiator,
            <N::Pattern as Pattern>::PreMessages,
            <N::Pattern as Pattern>::Messages,
            CP,
        >::new(provider, prologue);
        AsyncHandshake {
            inner: core.inner,
            stream,
            _marker: PhantomData,
        }
    }
}

impl<N, CP, Io>
    AsyncHandshake<
        N,
        Responder,
        <N::Pattern as Pattern>::PreMessages,
        <N::Pattern as Pattern>::Messages,
        CP,
        Io,
    >
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
{
    /// Begin an async handshake as the **responder** over `stream`.
    pub fn respond(provider: CP, prologue: &[u8], stream: Io) -> Self {
        let core = HandshakeState::<
            N,
            Responder,
            <N::Pattern as Pattern>::PreMessages,
            <N::Pattern as Pattern>::Messages,
            CP,
        >::new(provider, prologue);
        AsyncHandshake {
            inner: core.inner,
            stream,
            _marker: PhantomData,
        }
    }
}

// ═══════════════════════════════════════════════════════════════
//  Pre-message keys (the `<- s` / `-> s` directions)
// ═══════════════════════════════════════════════════════════════

// `<- s` + Initiator: the responder's static is the remote static.
impl<N, Tokens, Rest, Msgs, CP, Io>
    AsyncHandshake<N, Initiator, Cons<Message<ToInitiator, Tokens>, Rest>, Msgs, CP, Io>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Provide the remote party's static public key (`<- s`).
    pub fn set_rs(
        mut self,
        remote_static: <N::Curve as Curve>::PublicKey,
    ) -> AsyncHandshake<N, Initiator, Rest, Msgs, CP, Io> {
        self.inner.symmetric.mix_hash(remote_static.as_ref());
        self.inner.rs = Some(remote_static);
        AsyncHandshake {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        }
    }
}

// `<- s` + Responder: this is our own static key.
impl<N, Tokens, Rest, Msgs, CP, Io>
    AsyncHandshake<N, Responder, Cons<Message<ToInitiator, Tokens>, Rest>, Msgs, CP, Io>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Provide our local static key (`<- s`).
    pub fn set_s(
        mut self,
        static_key: CP::PrivateKey,
    ) -> Result<AsyncHandshake<N, Responder, Rest, Msgs, CP, Io>, HandshakeError> {
        let s_pub = self
            .inner
            .provider
            .public_key(&static_key)
            .map_err(|e| HandshakeError::Crypto(e.to_string()))?;
        self.inner.symmetric.mix_hash(s_pub.as_ref());
        self.inner.s_pub = Some(s_pub);
        self.inner.s = Some(static_key);
        Ok(AsyncHandshake {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        })
    }
}

// `-> s` + Initiator: this is our own static key.
impl<N, Tokens, Rest, Msgs, CP, Io>
    AsyncHandshake<N, Initiator, Cons<Message<ToResponder, Tokens>, Rest>, Msgs, CP, Io>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Provide our local static key (`-> s`).
    pub fn set_s(
        mut self,
        static_key: CP::PrivateKey,
    ) -> Result<AsyncHandshake<N, Initiator, Rest, Msgs, CP, Io>, HandshakeError> {
        let s_pub = self
            .inner
            .provider
            .public_key(&static_key)
            .map_err(|e| HandshakeError::Crypto(e.to_string()))?;
        self.inner.symmetric.mix_hash(s_pub.as_ref());
        self.inner.s_pub = Some(s_pub);
        self.inner.s = Some(static_key);
        Ok(AsyncHandshake {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        })
    }
}

// `-> s` + Responder: the initiator's static is the remote static.
impl<N, Tokens, Rest, Msgs, CP, Io>
    AsyncHandshake<N, Responder, Cons<Message<ToResponder, Tokens>, Rest>, Msgs, CP, Io>
where
    N: Protocol,
    CP: CryptoProviderAsync<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Provide the remote party's static public key (`-> s`).
    pub fn set_rs(
        mut self,
        remote_static: <N::Curve as Curve>::PublicKey,
    ) -> AsyncHandshake<N, Responder, Rest, Msgs, CP, Io> {
        self.inner.symmetric.mix_hash(remote_static.as_ref());
        self.inner.rs = Some(remote_static);
        AsyncHandshake {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        }
    }
}

// ═══════════════════════════════════════════════════════════════
//  Entry points: HandshakeState → Sending / Receiving
// ═══════════════════════════════════════════════════════════════

// Start a send message whose first token is E.
impl<N, R, Tokens, MsgRest, Dir, CP, Io>
    AsyncHandshake<N, R, Nil, Cons<Message<Dir, Cons<E, Tokens>>, MsgRest>, CP, Io>
where
    N: Protocol,
    R: Role<SendDir = Dir>,
    CP: CryptoProviderAsync<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
    Io: AsyncWrite + Unpin,
{
    /// Generate and stream our ephemeral public key (`e`).
    pub async fn e(
        mut self,
    ) -> Result<AsyncSending<N, R, Tokens, MsgRest, CP, Io>, HandshakeError> {
        async_stream_e(&mut self.inner, &mut self.stream).await?;
        Ok(AsyncSending {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        })
    }
}

// Start a send message whose first token is Psk.
impl<N, R, Tokens, MsgRest, Dir, CP, Io>
    AsyncHandshake<N, R, Nil, Cons<Message<Dir, Cons<Psk, Tokens>>, MsgRest>, CP, Io>
where
    N: Protocol,
    R: Role<SendDir = Dir>,
    CP: CryptoProviderAsync<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Mix the pre-shared key (`psk`) — writes nothing to the wire.
    pub async fn psk(
        mut self,
        psk_key: &crate::psk::Psk,
    ) -> Result<AsyncSending<N, R, Tokens, MsgRest, CP, Io>, HandshakeError> {
        do_psk(&mut self.inner, psk_key)?;
        Ok(AsyncSending {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        })
    }
}

// Start a send message whose first token is S.
impl<N, R, Tokens, MsgRest, Dir, CP, Io>
    AsyncHandshake<N, R, Nil, Cons<Message<Dir, Cons<S, Tokens>>, MsgRest>, CP, Io>
where
    N: Protocol,
    R: Role<SendDir = Dir>,
    CP: CryptoProviderAsync<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
    Io: AsyncWrite + Unpin,
{
    /// Encrypt and stream our static public key (`s`).
    pub async fn s(
        mut self,
        static_key: CP::PrivateKey,
    ) -> Result<AsyncSending<N, R, Tokens, MsgRest, CP, Io>, HandshakeError> {
        async_stream_s(&mut self.inner, &mut self.stream, static_key).await?;
        Ok(AsyncSending {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        })
    }
}

// Start receiving the next message (PreMsgs = Nil, message is ours to
// read). No bytes are read here — each token pulls exactly what it needs.
impl<N, R, Tokens, Rest, Dir, CP, Io>
    AsyncHandshake<N, R, Nil, Cons<Message<Dir, Tokens>, Rest>, CP, Io>
where
    N: Protocol,
    R: Role<RecvDir = Dir>,
    CP: CryptoProviderAsync<N::Curve>,
{
    /// Begin reading the next incoming handshake message.
    pub fn recv(self) -> AsyncReceiving<N, R, Tokens, Rest, CP, Io> {
        AsyncReceiving {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        }
    }
}

// ═══════════════════════════════════════════════════════════════
//  Macro: three-variant impls for a send token
// ═══════════════════════════════════════════════════════════════

/// Generate three `impl` blocks for a send-side token method. The body
/// has access to `inner: &mut HandshakeInner` and `stream: &mut Io`
/// (name it `_stream` for DH/psk tokens that write nothing) plus any
/// declared args.
macro_rules! async_send_token {
    (
        role: $R:ty,
        token: $Token:ty,
        method: $method:ident ($($arg:ident : $arg_ty:ty),*),
        bounds: [$($extra:tt)*],
        body: |$inner:ident, $stream:ident| { $($logic:tt)* }
    ) => {
        // Variant 1: more tokens after this one.
        impl<N, Next, More, MsgRest, CP, Io>
            AsyncSending<N, $R, Cons<$Token, Cons<Next, More>>, MsgRest, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProviderAsync<N::Curve>,
            Io: AsyncWrite + Unpin,
            $($extra)*
        {
            pub async fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<AsyncSending<N, $R, Cons<Next, More>, MsgRest, CP, Io>, HandshakeError> {
                {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                }
                Ok(AsyncSending { inner: self.inner, stream: self.stream, _marker: PhantomData })
            }
        }

        // Variant 2: last token, more messages.
        impl<N, NextMsg, MoreMsgs, CP, Io>
            AsyncSending<N, $R, Cons<$Token, Nil>, Cons<NextMsg, MoreMsgs>, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProviderAsync<N::Curve>,
            Io: AsyncWrite + Unpin,
            $($extra)*
        {
            pub async fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<AsyncHandshake<N, $R, Nil, Cons<NextMsg, MoreMsgs>, CP, Io>, HandshakeError> {
                {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                }
                send_message_tail_async(&mut self.inner, &mut self.stream).await?;
                Ok(AsyncHandshake { inner: self.inner, stream: self.stream, _marker: PhantomData })
            }
        }

        // Variant 3: last token, last message.
        impl<N, CP, Io>
            AsyncSending<N, $R, Cons<$Token, Nil>, Nil, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProviderAsync<N::Curve>,
            Io: AsyncWrite + Unpin,
            $($extra)*
        {
            pub async fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<AsyncTransport<N, Io>, HandshakeError> {
                {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                }
                send_message_tail_async(&mut self.inner, &mut self.stream).await?;
                let transport = recv_to_transport::<N, $R, CP>(self.inner);
                Ok(AsyncTransport { transport, stream: self.stream })
            }
        }
    };
}

// ═══════════════════════════════════════════════════════════════
//  Macro: three-variant impls for a recv token (no revealed key)
// ═══════════════════════════════════════════════════════════════

macro_rules! async_recv_token {
    (
        role: $R:ty,
        token: $Token:ty,
        method: $method:ident ($($arg:ident : $arg_ty:ty),*),
        bounds: [$($extra:tt)*],
        body: |$inner:ident, $stream:ident| { $($logic:tt)* }
    ) => {
        // Variant 1: more tokens.
        impl<N, Next, More, MsgRest, CP, Io>
            AsyncReceiving<N, $R, Cons<$Token, Cons<Next, More>>, MsgRest, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProviderAsync<N::Curve>,
            Io: AsyncRead + Unpin,
            $($extra)*
        {
            pub async fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<AsyncReceiving<N, $R, Cons<Next, More>, MsgRest, CP, Io>, HandshakeError> {
                {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                }
                Ok(AsyncReceiving { inner: self.inner, stream: self.stream, _marker: PhantomData })
            }
        }

        // Variant 2: last token, more messages.
        impl<N, NextMsg, MoreMsgs, CP, Io>
            AsyncReceiving<N, $R, Cons<$Token, Nil>, Cons<NextMsg, MoreMsgs>, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProviderAsync<N::Curve>,
            Io: AsyncRead + Unpin,
            $($extra)*
        {
            pub async fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<AsyncHandshake<N, $R, Nil, Cons<NextMsg, MoreMsgs>, CP, Io>, HandshakeError> {
                {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                }
                recv_message_tail_async(&mut self.inner, &mut self.stream).await?;
                Ok(AsyncHandshake { inner: self.inner, stream: self.stream, _marker: PhantomData })
            }
        }

        // Variant 3: last token, last message.
        impl<N, CP, Io>
            AsyncReceiving<N, $R, Cons<$Token, Nil>, Nil, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProviderAsync<N::Curve>,
            Io: AsyncRead + Unpin,
            $($extra)*
        {
            pub async fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<AsyncTransport<N, Io>, HandshakeError> {
                {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                }
                recv_message_tail_async(&mut self.inner, &mut self.stream).await?;
                let transport = recv_to_transport::<N, $R, CP>(self.inner);
                Ok(AsyncTransport { transport, stream: self.stream })
            }
        }
    };
}

// ═══════════════════════════════════════════════════════════════
//  Macro: recv token that reveals a public key (E or S)
// ═══════════════════════════════════════════════════════════════

macro_rules! async_recv_reveal_token {
    (
        role: $R:ty,
        token: $Token:ty,
        method: $method:ident ($($arg:ident : $arg_ty:ty),*),
        bounds: [$($extra:tt)*],
        body: |$inner:ident, $stream:ident| { $($logic:tt)* }
    ) => {
        // Variant 1: more tokens after this one.
        impl<N, Next, More, MsgRest, CP, Io>
            AsyncReceiving<N, $R, Cons<$Token, Cons<Next, More>>, MsgRest, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProviderAsync<N::Curve>,
            Io: AsyncRead + Unpin,
            $($extra)*
        {
            #[allow(clippy::type_complexity)]
            pub async fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<(<N::Curve as Curve>::PublicKey, AsyncReceiving<N, $R, Cons<Next, More>, MsgRest, CP, Io>), HandshakeError> {
                let revealed = {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                };
                Ok((revealed, AsyncReceiving { inner: self.inner, stream: self.stream, _marker: PhantomData }))
            }
        }

        // Variant 2: last token, more messages.
        impl<N, NextMsg, MoreMsgs, CP, Io>
            AsyncReceiving<N, $R, Cons<$Token, Nil>, Cons<NextMsg, MoreMsgs>, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProviderAsync<N::Curve>,
            Io: AsyncRead + Unpin,
            $($extra)*
        {
            #[allow(clippy::type_complexity)]
            pub async fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<(<N::Curve as Curve>::PublicKey, AsyncHandshake<N, $R, Nil, Cons<NextMsg, MoreMsgs>, CP, Io>), HandshakeError> {
                let revealed = {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                };
                recv_message_tail_async(&mut self.inner, &mut self.stream).await?;
                Ok((revealed, AsyncHandshake { inner: self.inner, stream: self.stream, _marker: PhantomData }))
            }
        }

        // Variant 3: last token, last message.
        impl<N, CP, Io>
            AsyncReceiving<N, $R, Cons<$Token, Nil>, Nil, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProviderAsync<N::Curve>,
            Io: AsyncRead + Unpin,
            $($extra)*
        {
            #[allow(clippy::type_complexity)]
            pub async fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<(<N::Curve as Curve>::PublicKey, AsyncTransport<N, Io>), HandshakeError> {
                let revealed = {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                };
                recv_message_tail_async(&mut self.inner, &mut self.stream).await?;
                let transport = recv_to_transport::<N, $R, CP>(self.inner);
                Ok((revealed, AsyncTransport { transport, stream: self.stream }))
            }
        }
    };
}

// ═══════════════════════════════════════════════════════════════
//  Token: E (role-independent)
// ═══════════════════════════════════════════════════════════════

async_send_token! {
    role: Initiator, token: E, method: e(), bounds: [],
    body: |inner, stream| { async_stream_e(inner, stream).await?; }
}
async_send_token! {
    role: Responder, token: E, method: e(), bounds: [],
    body: |inner, stream| { async_stream_e(inner, stream).await?; }
}
async_recv_reveal_token! {
    role: Initiator, token: E, method: e(), bounds: [],
    body: |inner, stream| { async_read_e(inner, stream).await? }
}
async_recv_reveal_token! {
    role: Responder, token: E, method: e(), bounds: [],
    body: |inner, stream| { async_read_e(inner, stream).await? }
}

// ═══════════════════════════════════════════════════════════════
//  Token: S
// ═══════════════════════════════════════════════════════════════

async_send_token! {
    role: Initiator, token: S, method: s(static_key: CP::PrivateKey), bounds: [],
    body: |inner, stream| { async_stream_s(inner, stream, static_key).await?; }
}
async_send_token! {
    role: Responder, token: S, method: s(static_key: CP::PrivateKey), bounds: [],
    body: |inner, stream| { async_stream_s(inner, stream, static_key).await?; }
}
async_recv_reveal_token! {
    role: Initiator, token: S, method: s(), bounds: [],
    body: |inner, stream| { async_read_s(inner, stream).await? }
}
async_recv_reveal_token! {
    role: Responder, token: S, method: s(), bounds: [],
    body: |inner, stream| { async_read_s(inner, stream).await? }
}

// ═══════════════════════════════════════════════════════════════
//  Token: Ee (role-independent)
// ═══════════════════════════════════════════════════════════════

async_send_token! {
    role: Initiator, token: Ee, method: ee(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_ee(inner).await?; }
}
async_send_token! {
    role: Responder, token: Ee, method: ee(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_ee(inner).await?; }
}
async_recv_token! {
    role: Initiator, token: Ee, method: ee(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_ee(inner).await?; }
}
async_recv_token! {
    role: Responder, token: Ee, method: ee(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_ee(inner).await?; }
}

// ═══════════════════════════════════════════════════════════════
//  Token: Es (role-dependent)
// ═══════════════════════════════════════════════════════════════

async_send_token! {
    role: Initiator, token: Es, method: es(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_es_initiator(inner).await?; }
}
async_recv_token! {
    role: Initiator, token: Es, method: es(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_es_initiator(inner).await?; }
}
async_send_token! {
    role: Responder, token: Es, method: es(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_es_responder(inner).await?; }
}
async_recv_token! {
    role: Responder, token: Es, method: es(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_es_responder(inner).await?; }
}

// ═══════════════════════════════════════════════════════════════
//  Token: Se (role-dependent)
// ═══════════════════════════════════════════════════════════════

async_send_token! {
    role: Initiator, token: Se, method: se(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_se_initiator(inner).await?; }
}
async_recv_token! {
    role: Initiator, token: Se, method: se(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_se_initiator(inner).await?; }
}
async_send_token! {
    role: Responder, token: Se, method: se(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_se_responder(inner).await?; }
}
async_recv_token! {
    role: Responder, token: Se, method: se(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_se_responder(inner).await?; }
}

// ═══════════════════════════════════════════════════════════════
//  Token: Ss (role-independent)
// ═══════════════════════════════════════════════════════════════

async_send_token! {
    role: Initiator, token: Ss, method: ss(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_ss(inner).await?; }
}
async_send_token! {
    role: Responder, token: Ss, method: ss(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_ss(inner).await?; }
}
async_recv_token! {
    role: Initiator, token: Ss, method: ss(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_ss(inner).await?; }
}
async_recv_token! {
    role: Responder, token: Ss, method: ss(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { do_ss(inner).await?; }
}

// ═══════════════════════════════════════════════════════════════
//  Token: Psk (role-independent)
// ═══════════════════════════════════════════════════════════════

async_send_token! {
    role: Initiator, token: Psk, method: psk(psk_key: &crate::psk::Psk), bounds: [],
    body: |inner, _stream| { do_psk(inner, psk_key)?; }
}
async_send_token! {
    role: Responder, token: Psk, method: psk(psk_key: &crate::psk::Psk), bounds: [],
    body: |inner, _stream| { do_psk(inner, psk_key)?; }
}
async_recv_token! {
    role: Initiator, token: Psk, method: psk(psk_key: &crate::psk::Psk), bounds: [],
    body: |inner, _stream| { do_psk(inner, psk_key)?; }
}
async_recv_token! {
    role: Responder, token: Psk, method: psk(psk_key: &crate::psk::Psk), bounds: [],
    body: |inner, _stream| { do_psk(inner, psk_key)?; }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::curve::p256::SoftwareCryptoProvider;
    use crate::curve::{CryptoKeys, CryptoProviderAsync};
    use crate::noise::{Blake2b, ChaChaPoly, IKpsk1, Initiator, K, N, Noise, P256, Responder};
    use crate::noise_message_size;
    use crate::psk::Psk;
    use std::io::Cursor;

    type Seal = Noise<N, P256, ChaChaPoly, Blake2b>;
    type Channel = Noise<IKpsk1, P256, ChaChaPoly, Blake2b>;
    type NoiseK = Noise<K, P256, ChaChaPoly, Blake2b>;

    /// Full Noise N seal/open over `tokio::io`, with a real transport
    /// round-trip — proves wire correctness end-to-end (any wrong byte
    /// would break the AEAD tag). `Vec<u8>` is a tokio `AsyncWrite`;
    /// `Cursor<Vec<u8>>` is a tokio `AsyncRead`.
    #[tokio::test]
    async fn n_async_seal_open_roundtrip() {
        let provider = SoftwareCryptoProvider;
        let recipient_static = provider.generate_static_key_async().await.unwrap();
        let recipient_pub = provider.public_key(&recipient_static).unwrap();

        let sealer = AsyncHandshake::<Seal, Initiator, _, _, _, _>::initiate(
            SoftwareCryptoProvider,
            &[],
            Vec::<u8>::new(),
        )
        .set_rs(recipient_pub);
        let sealer_done = sealer.e().await.unwrap().es().await.unwrap();
        let (mut send_transport, wire) = sealer_done.into_parts();
        assert_eq!(wire.len(), 81);

        let payload = [0x42u8; 32];
        let mut sealed = [0u8; 48];
        let sealed_len = send_transport.send(&payload, &mut sealed).unwrap();

        let opener = AsyncHandshake::<Seal, Responder, _, _, _, _>::respond(
            SoftwareCryptoProvider,
            &[],
            Cursor::new(wire),
        )
        .set_s(recipient_static)
        .unwrap();
        let (_revealed_e, recv) = opener.recv().e().await.unwrap();
        let mut recv_transport = recv.es().await.unwrap();

        assert_eq!(
            send_transport.session_id(),
            recv_transport.transport().session_id()
        );

        let mut opened = [0u8; 32];
        let opened_len = recv_transport
            .transport()
            .receive(&sealed[..sealed_len], &mut opened)
            .unwrap();
        assert_eq!(opened_len, 32);
        assert_eq!(opened, payload);
    }

    /// A corrupted ephemeral on the wire must make the responder's `es`
    /// fail (DH mismatch → payload-tag verification fails).
    #[tokio::test]
    async fn n_async_tampered_ephemeral_rejected() {
        let provider = SoftwareCryptoProvider;
        let recipient_static = provider.generate_static_key_async().await.unwrap();
        let recipient_pub = provider.public_key(&recipient_static).unwrap();

        let sealer = AsyncHandshake::<Seal, Initiator, _, _, _, _>::initiate(
            SoftwareCryptoProvider,
            &[],
            Vec::<u8>::new(),
        )
        .set_rs(recipient_pub);
        let (_t, mut wire) = sealer.e().await.unwrap().es().await.unwrap().into_parts();
        wire[1] ^= 0xFF; // flip a byte in the ephemeral public key

        let opener = AsyncHandshake::<Seal, Responder, _, _, _, _>::respond(
            SoftwareCryptoProvider,
            &[],
            Cursor::new(wire),
        )
        .set_s(recipient_static)
        .unwrap();

        match opener.recv().e().await {
            Err(_) => {}
            Ok((_e, recv)) => assert!(recv.es().await.is_err()),
        }
    }

    /// The same async handshake works with the **Secure Enclave**
    /// provider — its blocking calls are offloaded via `spawn_blocking`,
    /// which the `#[tokio::test]` runtime supports (using software-backed
    /// `SecKey`s so the test needs no SE hardware).
    #[cfg(any(target_os = "macos", target_os = "ios"))]
    #[tokio::test]
    async fn n_async_seal_open_with_secure_enclave_provider() {
        use crate::curve::p256::SecureEnclaveCryptoProvider;

        let provider = SecureEnclaveCryptoProvider;
        let recipient_static = provider.generate_ephemeral_key_async().await.unwrap();
        let recipient_pub = provider.public_key(&recipient_static).unwrap();

        let sealer = AsyncHandshake::<Seal, Initiator, _, _, _, _>::initiate(
            SecureEnclaveCryptoProvider,
            &[],
            Vec::<u8>::new(),
        )
        .set_rs(recipient_pub);
        let (mut send_transport, wire) = sealer.e().await.unwrap().es().await.unwrap().into_parts();
        assert_eq!(wire.len(), 81);

        let payload = [0x42u8; 32];
        let mut sealed = [0u8; 48];
        let sealed_len = send_transport.send(&payload, &mut sealed).unwrap();

        let opener = AsyncHandshake::<Seal, Responder, _, _, _, _>::respond(
            SecureEnclaveCryptoProvider,
            &[],
            Cursor::new(wire),
        )
        .set_s(recipient_static)
        .unwrap();
        let (_revealed_e, recv) = opener.recv().e().await.unwrap();
        let mut recv_transport = recv.es().await.unwrap();

        assert_eq!(
            send_transport.session_id(),
            recv_transport.transport().session_id()
        );
        let mut opened = [0u8; 32];
        let opened_len = recv_transport
            .transport()
            .receive(&sealed[..sealed_len], &mut opened)
            .unwrap();
        assert_eq!(&opened[..opened_len], &payload);
    }

    /// **Cross-check against the snow-verified buffer core.** A full
    /// IKpsk1 handshake (`-> e,es,s,ss,psk` / `<- e,ee,se`) driven with
    /// the `io_async` **initiator** against the buffer-core **responder**
    /// (the snow-interop-verified path), exchanged over a
    /// `tokio::io::duplex` pipe. Any divergence surfaces as a tag failure.
    #[tokio::test]
    async fn ikpsk1_async_initiator_vs_buffer_core() {
        let provider = SoftwareCryptoProvider;
        let initiator_static = provider.generate_static_key_async().await.unwrap();
        let initiator_pub = provider.public_key(&initiator_static).unwrap();
        let responder_static = provider.generate_static_key_async().await.unwrap();
        let responder_pub = provider.public_key(&responder_static).unwrap();
        let psk = Psk::from_bytes([0xAA; 32]);

        let (io_stream, mut peer) = tokio::io::duplex(4096);

        // io_async initiator drives msg1 (-> e, es, s, ss, psk).
        let i_hs = AsyncHandshake::<Channel, Initiator, _, _, _, _>::initiate(
            SoftwareCryptoProvider,
            &[],
            io_stream,
        )
        .set_rs(responder_pub);
        let i_hs = i_hs
            .e()
            .await
            .unwrap()
            .es()
            .await
            .unwrap()
            .s(initiator_static)
            .await
            .unwrap()
            .ss()
            .await
            .unwrap()
            .psk(&psk)
            .await
            .unwrap();
        let mut msg1 = vec![0u8; 162];
        peer.read_exact(&mut msg1).await.unwrap();

        // buffer-core responder consumes msg1 and produces msg2.
        let r_hs = Channel::respond(SoftwareCryptoProvider, &[])
            .set_s(responder_static)
            .unwrap();
        let (_e, recv) = r_hs.read(&msg1).unwrap().e().await.unwrap();
        let recv = recv.es().await.unwrap();
        let (revealed_i_pub, recv) = recv.s().await.unwrap();
        assert_eq!(revealed_i_pub, initiator_pub);
        let recv = recv.ss().await.unwrap();
        let r_hs = recv.psk(&psk).await.unwrap();

        let mut msg2_buf = [0u8;
            noise_message_size!(curve: P256, cipher: ChaChaPoly, has_psk: true, keyed: true, tokens: [E, Ee, Se],)];
        let (msg2, r_transport) = r_hs
            .e(&mut msg2_buf)
            .await
            .unwrap()
            .ee()
            .await
            .unwrap()
            .se()
            .await
            .unwrap();
        peer.write_all(msg2).await.unwrap();
        peer.flush().await.unwrap();

        // io_async initiator consumes msg2 (<- e, ee, se).
        let (_revealed_r_e, recv) = i_hs.recv().e().await.unwrap();
        let i_transport = recv.ee().await.unwrap().se().await.unwrap();

        assert_eq!(i_transport.transport.session_id(), r_transport.session_id());
    }

    /// Mirror with roles flipped: `io_async` **responder** against the
    /// buffer-core **initiator** — anchors `io_async`'s responder-role
    /// path to the snow-verified core.
    #[tokio::test]
    async fn ikpsk1_async_responder_vs_buffer_core() {
        let provider = SoftwareCryptoProvider;
        let initiator_static = provider.generate_static_key_async().await.unwrap();
        let initiator_pub = provider.public_key(&initiator_static).unwrap();
        let responder_static = provider.generate_static_key_async().await.unwrap();
        let responder_pub = provider.public_key(&responder_static).unwrap();
        let psk = Psk::from_bytes([0xBB; 32]);

        // buffer-core initiator builds msg1.
        let i_hs = Channel::initiate(SoftwareCryptoProvider, &[]).set_rs(responder_pub);
        let mut msg1_buf = [0u8;
            noise_message_size!(curve: P256, cipher: ChaChaPoly, has_psk: true, keyed: false, tokens: [E, Es, S, Ss, Psk],)];
        let (msg1, i_hs) = i_hs
            .e(&mut msg1_buf)
            .await
            .unwrap()
            .es()
            .await
            .unwrap()
            .s(initiator_static)
            .await
            .unwrap()
            .ss()
            .await
            .unwrap()
            .psk(&psk)
            .await
            .unwrap();
        let msg1 = msg1.to_vec();

        let (io_stream, mut peer) = tokio::io::duplex(4096);
        peer.write_all(&msg1).await.unwrap();
        peer.flush().await.unwrap();

        // io_async responder consumes msg1, then sends msg2.
        let r_hs = AsyncHandshake::<Channel, Responder, _, _, _, _>::respond(
            SoftwareCryptoProvider,
            &[],
            io_stream,
        )
        .set_s(responder_static)
        .unwrap();
        let (_e, recv) = r_hs.recv().e().await.unwrap();
        let recv = recv.es().await.unwrap();
        let (revealed_i_pub, recv) = recv.s().await.unwrap();
        assert_eq!(revealed_i_pub, initiator_pub);
        let recv = recv.ss().await.unwrap();
        let r_hs = recv.psk(&psk).await.unwrap();
        let r_transport = r_hs
            .e()
            .await
            .unwrap()
            .ee()
            .await
            .unwrap()
            .se()
            .await
            .unwrap();
        let mut msg2 = vec![0u8; 81];
        peer.read_exact(&mut msg2).await.unwrap();

        // buffer-core initiator consumes msg2.
        let (_re, recv) = i_hs.read(&msg2).unwrap().e().await.unwrap();
        let i_transport = recv.ee().await.unwrap().se().await.unwrap();

        assert_eq!(i_transport.session_id(), r_transport.transport.session_id());
    }

    /// Noise K (`-> e, es, ss`, pre `-> s, <- s`) round-trip over
    /// `tokio::io` — single-message, exercises the `-> s` pre-message
    /// setters and the `ss` token end-to-end.
    #[tokio::test]
    async fn k_async_round_trip() {
        let provider = SoftwareCryptoProvider;
        let alice_static = provider.generate_static_key_async().await.unwrap();
        let alice_pub = provider.public_key(&alice_static).unwrap();
        let bob_static = provider.generate_static_key_async().await.unwrap();
        let bob_pub = provider.public_key(&bob_static).unwrap();
        let payload = [0x42u8; 32];

        // initiator: pre -> s (alice), <- s (bob); msg1 -> e, es, ss.
        let sealer = AsyncHandshake::<NoiseK, Initiator, _, _, _, _>::initiate(
            SoftwareCryptoProvider,
            &[],
            Vec::<u8>::new(),
        )
        .set_s(alice_static)
        .unwrap()
        .set_rs(bob_pub);
        let (mut send_transport, wire) = sealer
            .e()
            .await
            .unwrap()
            .es()
            .await
            .unwrap()
            .ss()
            .await
            .unwrap()
            .into_parts();
        assert_eq!(wire.len(), 81);
        let mut sealed = [0u8; 48];
        let n = send_transport.send(&payload, &mut sealed).unwrap();

        // responder: pre -> s (alice via set_rs), <- s (bob via set_s).
        let opener = AsyncHandshake::<NoiseK, Responder, _, _, _, _>::respond(
            SoftwareCryptoProvider,
            &[],
            Cursor::new(wire),
        )
        .set_rs(alice_pub)
        .set_s(bob_static)
        .unwrap();
        let (_e, recv) = opener.recv().e().await.unwrap();
        let mut recv_transport = recv.es().await.unwrap().ss().await.unwrap();
        assert_eq!(
            send_transport.session_id(),
            recv_transport.transport().session_id()
        );
        let mut opened = [0u8; 32];
        let on = recv_transport
            .transport()
            .receive(&sealed[..n], &mut opened)
            .unwrap();
        assert_eq!(&opened[..on], &payload);
    }
}
