//! Blocking `std::io` handshake adapter.
//!
//! A synchronous, [`std::io::Read`]/[`std::io::Write`] surface over the
//! same type-state Noise handshake as the buffer core — the caller
//! hands the handshake a stream and drives it with a fluent token chain
//! that reads/writes the wire directly, no `.await`, no caller-sized
//! buffer:
//!
//! ```ignore
//! use hiss::noise::*;
//! type Seal = Noise<N, P256, ChaChaPoly, Blake2b>;
//!
//! // initiator — `stream: impl std::io::Write`
//! let i = SyncHandshake::<Seal, Initiator, _, _, _, _>::initiate(provider, &[], stream)
//!     .set_rs(recipient_pub);
//! let mut sealed = i.e()?.es()?;          // msg1 streamed to the wire; `sealed` owns the stream
//!
//! // responder — `stream: impl std::io::Read`
//! let r = SyncHandshake::<Seal, Responder, _, _, _, _>::respond(provider, &[], stream)
//!     .set_s(recipient_static)?;
//! let (their_e, recv) = r.recv().e()?;    // each token reads exactly its bytes off the wire
//! let mut opened = recv.es()?;
//! ```
//!
//! # Design
//!
//! This layer is **purely additive**: the buffer-based core
//! ([`HandshakeState`]/[`Sending`]/[`Receiving`](super::handshake)) is
//! untouched and remains canonical. Each token method here threads its
//! compile-time [`WireSize`](super::tokens::WireSize)-sized bytes through
//! a small fixed stack scratch and streams them to the stream, so the
//! bytes on the wire are identical to the buffer path; only buffer
//! ownership and the I/O differ. The structure mirrors
//! [`process`](super::process): three `impl` blocks per token per context
//! (more-tokens / last-token-more-messages / last-token-last-message),
//! generated by macros.
//!
//! # Synchronous crypto
//!
//! The blocking handshake is generic over [`CryptoProvider`] — the
//! synchronous provider surface — and calls its `*_sync` methods
//! directly (no executor, no future-polling). Both backends implement
//! it: software (`eccoxide`) natively, and Apple **Secure Enclave**
//! (whose Security-framework calls are synchronous, blocking C
//! functions) by running them on the calling thread — exactly as Apple's
//! libraries expose them. An async-only provider cannot be used here: it
//! is a *compile* error (it does not implement [`CryptoProvider`]).
//!
//! The provider-free helpers (`recv_e`/`recv_s`/`send_s`/`send_payload`/
//! `recv_payload`/`do_psk`/`recv_to_transport`) are shared verbatim with
//! the buffer core via [`process`](super::process); only the
//! DH/ephemeral steps that call the provider have synchronous mirrors
//! here (calling `*_sync`).
//!
//! # Flushing & cancellation
//!
//! Each completed outgoing handshake message is flushed before the call
//! returns, so it reaches the peer even over a buffered writer (and a
//! multi-message handshake does not deadlock waiting on unflushed bytes).
//! Bytes are streamed per token and crypto state advances as they are
//! produced, so a mid-handshake I/O error is **fatal and unrecoverable**
//! — drop the whole handshake and the connection; there is no per-token
//! retry (the same contract as `tokio-rustls`).

use std::io::{Read, Write};
use std::marker::PhantomData;

use super::Protocol;
use super::buffers::{RecvBuffer, SendBuffer};
use super::cipher::Cipher;
use super::error::HandshakeError;
use super::handshake::{HandshakeInner, HandshakeState};
use super::hash::Hash;
use super::pattern::Pattern;
use super::process::{do_psk, recv_e, recv_payload, recv_s, recv_to_transport, send_payload, send_s};
use super::role::{Initiator, Responder, Role};
use super::tokens::*;
use super::transport::Transport;
use crate::curve::{CryptoKeys, CryptoProvider, Curve};

/// Largest single contiguous write/read a token produces: an encrypted
/// static key (`PUBLIC_KEY_SIZE + TAG_SIZE`). 128 bytes covers every
/// supported curve/cipher with margin; the payload tag uses far less.
const TOKEN_SCRATCH: usize = 128;

// ── Synchronous token crypto ─────────────────────────────────────
//
// Mirror the provider-calling helpers in `process.rs`, but call the
// synchronous `CryptoProvider` methods instead of awaiting. The
// provider-free helpers are reused from `process.rs` directly.

/// Generate our ephemeral, write its public key, mix it in.
fn sync_send_e<Cu, Ci, H, CP>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    buffer: &mut SendBuffer<'_>,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Cu::PublicKey: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoProvider<Cu>,
{
    let e = inner
        .provider
        .generate_ephemeral_key()
        .map_err(|e| HandshakeError::Crypto(e.to_string()))?;
    let e_pub = inner
        .provider
        .public_key(&e)
        .map_err(|e| HandshakeError::Crypto(e.to_string()))?;
    buffer.write(e_pub.as_ref());
    inner.symmetric.mix_hash(e_pub.as_ref());
    if inner.has_psk {
        inner.symmetric.mix_key(e_pub.as_ref());
    }
    inner.e = Some(e);
    inner.e_pub = Some(e_pub);
    Ok(())
}

/// Initiator `es`: DH(e, rs).
fn sync_do_es_initiator<Cu, Ci, H, CP>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Cu::SharedSecret: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoProvider<Cu>,
{
    let e = inner
        .e
        .as_ref()
        .ok_or(HandshakeError::MissingEphemeralKey)?;
    let rs = inner
        .rs
        .as_ref()
        .ok_or(HandshakeError::MissingRemoteStatic)?;
    let ss = inner
        .provider
        .dh(e, rs)
        .map_err(|e| HandshakeError::Crypto(e.to_string()))?;
    inner.symmetric.mix_key(ss.as_ref());
    Ok(())
}

/// Responder `es`: DH(s, re).
fn sync_do_es_responder<Cu, Ci, H, CP>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Cu::SharedSecret: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoProvider<Cu>,
{
    let s = inner.s.as_ref().ok_or(HandshakeError::MissingStaticKey)?;
    let re = inner
        .re
        .as_ref()
        .ok_or(HandshakeError::MissingRemoteEphemeral)?;
    let ss = inner
        .provider
        .dh(s, re)
        .map_err(|e| HandshakeError::Crypto(e.to_string()))?;
    inner.symmetric.mix_key(ss.as_ref());
    Ok(())
}

/// `ee`: DH(e, re) (role-independent).
fn sync_do_ee<Cu, Ci, H, CP>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Cu::SharedSecret: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoProvider<Cu>,
{
    let e = inner
        .e
        .as_ref()
        .ok_or(HandshakeError::MissingEphemeralKey)?;
    let re = inner
        .re
        .as_ref()
        .ok_or(HandshakeError::MissingRemoteEphemeral)?;
    let ss = inner
        .provider
        .dh(e, re)
        .map_err(|e| HandshakeError::Crypto(e.to_string()))?;
    inner.symmetric.mix_key(ss.as_ref());
    Ok(())
}

/// Initiator `se`: DH(s, re).
fn sync_do_se_initiator<Cu, Ci, H, CP>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Cu::SharedSecret: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoProvider<Cu>,
{
    let s = inner.s.as_ref().ok_or(HandshakeError::MissingStaticKey)?;
    let re = inner
        .re
        .as_ref()
        .ok_or(HandshakeError::MissingRemoteEphemeral)?;
    let ss = inner
        .provider
        .dh(s, re)
        .map_err(|e| HandshakeError::Crypto(e.to_string()))?;
    inner.symmetric.mix_key(ss.as_ref());
    Ok(())
}

/// Responder `se`: DH(e, rs).
fn sync_do_se_responder<Cu, Ci, H, CP>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Cu::SharedSecret: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoProvider<Cu>,
{
    let e = inner
        .e
        .as_ref()
        .ok_or(HandshakeError::MissingEphemeralKey)?;
    let rs = inner
        .rs
        .as_ref()
        .ok_or(HandshakeError::MissingRemoteStatic)?;
    let ss = inner
        .provider
        .dh(e, rs)
        .map_err(|e| HandshakeError::Crypto(e.to_string()))?;
    inner.symmetric.mix_key(ss.as_ref());
    Ok(())
}

/// `ss`: DH(s, rs) (role-independent).
fn sync_do_ss<Cu, Ci, H, CP>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Cu::SharedSecret: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoProvider<Cu>,
{
    let s = inner.s.as_ref().ok_or(HandshakeError::MissingStaticKey)?;
    let rs = inner
        .rs
        .as_ref()
        .ok_or(HandshakeError::MissingRemoteStatic)?;
    let ss = inner
        .provider
        .dh(s, rs)
        .map_err(|e| HandshakeError::Crypto(e.to_string()))?;
    inner.symmetric.mix_key(ss.as_ref());
    Ok(())
}

// ── Streaming token helpers (compute bytes → write/read the wire) ──

/// `e` (send): generate + mix the ephemeral and stream its public key.
fn sync_stream_e<Cu, Ci, H, CP, Io>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    stream: &mut Io,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Cu::PublicKey: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoProvider<Cu>,
    Io: Write,
{
    let mut scratch = [0u8; TOKEN_SCRATCH];
    let mut buffer = SendBuffer::new(&mut scratch);
    sync_send_e(inner, &mut buffer)?;
    stream.write_all(buffer.finish())?;
    Ok(())
}

/// `s` (send): encrypt + mix the static key and stream it.
fn sync_stream_s<Cu, Ci, H, CP, Io>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    stream: &mut Io,
    static_key: CP::PrivateKey,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Cu::PublicKey: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoKeys<Cu>,
    Io: Write,
{
    let mut scratch = [0u8; TOKEN_SCRATCH];
    let mut buffer = SendBuffer::new(&mut scratch);
    send_s(inner, &mut buffer, static_key)?;
    stream.write_all(buffer.finish())?;
    Ok(())
}

/// `e` (recv): read the remote ephemeral public key and mix it in.
fn sync_read_e<Cu, Ci, H, CP, Io>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    stream: &mut Io,
) -> Result<Cu::PublicKey, HandshakeError>
where
    Cu: Curve,
    Cu::PublicKey: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoKeys<Cu>,
    Io: Read,
{
    let pk_size = Cu::PUBLIC_KEY_SIZE;
    let mut scratch = [0u8; TOKEN_SCRATCH];
    stream.read_exact(&mut scratch[..pk_size])?;
    let mut buffer = RecvBuffer::new(&scratch[..pk_size]);
    recv_e(inner, &mut buffer)
}

/// `s` (recv): read + decrypt the remote static key and mix it in.
fn sync_read_s<Cu, Ci, H, CP, Io>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    stream: &mut Io,
) -> Result<Cu::PublicKey, HandshakeError>
where
    Cu: Curve,
    Cu::PublicKey: AsRef<[u8]>,
    Ci: Cipher,
    H: Hash,
    CP: CryptoKeys<Cu>,
    Io: Read,
{
    let wire_len = if inner.symmetric.has_key() {
        Cu::PUBLIC_KEY_SIZE + Ci::TAG_SIZE
    } else {
        Cu::PUBLIC_KEY_SIZE
    };
    let mut scratch = [0u8; TOKEN_SCRATCH];
    stream.read_exact(&mut scratch[..wire_len])?;
    let mut buffer = RecvBuffer::new(&scratch[..wire_len]);
    recv_s(inner, &mut buffer)
}

/// Close an outgoing message: encrypt-and-hash the empty payload, stream
/// the resulting tag (`TAG_SIZE` bytes when keyed, nothing otherwise),
/// and flush so a buffered writer releases the whole message.
fn send_message_tail<Cu, Ci, H, CP, Io>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    stream: &mut Io,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Ci: Cipher,
    H: Hash,
    CP: CryptoKeys<Cu>,
    Io: Write,
{
    let tag_len = if inner.symmetric.has_key() {
        Ci::TAG_SIZE
    } else {
        0
    };
    let mut scratch = [0u8; TOKEN_SCRATCH];
    let mut buffer = SendBuffer::new(&mut scratch[..tag_len]);
    send_payload(inner, &mut buffer)?;
    stream.write_all(buffer.finish())?;
    stream.flush()?;
    Ok(())
}

/// Close an incoming message: read and verify the trailing empty-payload
/// tag (`TAG_SIZE` bytes when keyed, nothing otherwise).
fn recv_message_tail<Cu, Ci, H, CP, Io>(
    inner: &mut HandshakeInner<Cu, Ci, H, CP>,
    stream: &mut Io,
) -> Result<(), HandshakeError>
where
    Cu: Curve,
    Ci: Cipher,
    H: Hash,
    CP: CryptoKeys<Cu>,
    Io: Read,
{
    let tag_len = if inner.symmetric.has_key() {
        Ci::TAG_SIZE
    } else {
        0
    };
    let mut scratch = [0u8; TOKEN_SCRATCH];
    stream.read_exact(&mut scratch[..tag_len])?;
    let mut buffer = RecvBuffer::new(&scratch[..tag_len]);
    recv_payload(inner, &mut buffer)
}

// ═══════════════════════════════════════════════════════════════
//  State types — mirror the buffer core, but own the stream `Io`
//  instead of borrowing a buffer (so there is no `'a` lifetime).
// ═══════════════════════════════════════════════════════════════

/// Synchronous handshake state between messages. See the module docs.
pub struct SyncHandshake<N, R, Stage, Msgs, CP, Io>
where
    N: Protocol,
    CP: CryptoProvider<N::Curve>,
{
    inner: HandshakeInner<N::Curve, N::Cipher, N::Hash, CP>,
    stream: Io,
    _marker: PhantomData<fn() -> (N, R, Stage, Msgs)>,
}

/// Synchronous state within an outgoing message.
pub struct SyncSending<N, R, Tokens, MsgRest, CP, Io>
where
    N: Protocol,
    CP: CryptoProvider<N::Curve>,
{
    inner: HandshakeInner<N::Curve, N::Cipher, N::Hash, CP>,
    stream: Io,
    _marker: PhantomData<fn() -> (N, R, Tokens, MsgRest)>,
}

/// Synchronous state within an incoming message.
pub struct SyncReceiving<N, R, Tokens, MsgRest, CP, Io>
where
    N: Protocol,
    CP: CryptoProvider<N::Curve>,
{
    inner: HandshakeInner<N::Curve, N::Cipher, N::Hash, CP>,
    stream: Io,
    _marker: PhantomData<fn() -> (N, R, Tokens, MsgRest)>,
}

/// Completed handshake plus the stream it ran over.
///
/// Like a TLS stream, the post-handshake [`Transport`] and the `Io` it
/// rides on are bundled together; [`into_parts`](Self::into_parts)
/// recovers them separately.
pub struct SyncTransport<N: Protocol, Io> {
    transport: Transport<N>,
    stream: Io,
}

impl<N: Protocol, Io> SyncTransport<N, Io> {
    /// The post-handshake transport cipher pair.
    pub fn transport(&mut self) -> &mut Transport<N> {
        &mut self.transport
    }

    /// The underlying stream.
    pub fn stream(&mut self) -> &mut Io {
        &mut self.stream
    }

    /// Split into the transport and the stream.
    pub fn into_parts(self) -> (Transport<N>, Io) {
        (self.transport, self.stream)
    }
}

// ═══════════════════════════════════════════════════════════════
//  Construction
// ═══════════════════════════════════════════════════════════════

impl<N, CP, Io>
    SyncHandshake<
        N,
        Initiator,
        <N::Pattern as Pattern>::PreMessages,
        <N::Pattern as Pattern>::Messages,
        CP,
        Io,
    >
where
    N: Protocol,
    CP: CryptoProvider<N::Curve>,
{
    /// Begin a blocking handshake as the **initiator** over `stream`.
    pub fn initiate(provider: CP, prologue: &[u8], stream: Io) -> Self {
        let core = HandshakeState::<
            N,
            Initiator,
            <N::Pattern as Pattern>::PreMessages,
            <N::Pattern as Pattern>::Messages,
            CP,
        >::new(provider, prologue);
        SyncHandshake {
            inner: core.inner,
            stream,
            _marker: PhantomData,
        }
    }
}

impl<N, CP, Io>
    SyncHandshake<
        N,
        Responder,
        <N::Pattern as Pattern>::PreMessages,
        <N::Pattern as Pattern>::Messages,
        CP,
        Io,
    >
where
    N: Protocol,
    CP: CryptoProvider<N::Curve>,
{
    /// Begin a blocking handshake as the **responder** over `stream`.
    pub fn respond(provider: CP, prologue: &[u8], stream: Io) -> Self {
        let core = HandshakeState::<
            N,
            Responder,
            <N::Pattern as Pattern>::PreMessages,
            <N::Pattern as Pattern>::Messages,
            CP,
        >::new(provider, prologue);
        SyncHandshake {
            inner: core.inner,
            stream,
            _marker: PhantomData,
        }
    }
}

// ═══════════════════════════════════════════════════════════════
//  Pre-message keys (the `<- s` / `-> s` directions)
// ═══════════════════════════════════════════════════════════════

// `<- s` + Initiator: the responder's static is the remote static.
impl<N, Tokens, Rest, Msgs, CP, Io>
    SyncHandshake<N, Initiator, Cons<Message<ToInitiator, Tokens>, Rest>, Msgs, CP, Io>
where
    N: Protocol,
    CP: CryptoProvider<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Provide the remote party's static public key (`<- s`).
    pub fn set_rs(
        mut self,
        remote_static: <N::Curve as Curve>::PublicKey,
    ) -> SyncHandshake<N, Initiator, Rest, Msgs, CP, Io> {
        self.inner.symmetric.mix_hash(remote_static.as_ref());
        self.inner.rs = Some(remote_static);
        SyncHandshake {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        }
    }
}

// `<- s` + Responder: this is our own static key.
impl<N, Tokens, Rest, Msgs, CP, Io>
    SyncHandshake<N, Responder, Cons<Message<ToInitiator, Tokens>, Rest>, Msgs, CP, Io>
where
    N: Protocol,
    CP: CryptoProvider<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Provide our local static key (`<- s`).
    pub fn set_s(
        mut self,
        static_key: CP::PrivateKey,
    ) -> Result<SyncHandshake<N, Responder, Rest, Msgs, CP, Io>, HandshakeError> {
        let s_pub = self
            .inner
            .provider
            .public_key(&static_key)
            .map_err(|e| HandshakeError::Crypto(e.to_string()))?;
        self.inner.symmetric.mix_hash(s_pub.as_ref());
        self.inner.s_pub = Some(s_pub);
        self.inner.s = Some(static_key);
        Ok(SyncHandshake {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        })
    }
}

// `-> s` + Initiator: this is our own static key.
impl<N, Tokens, Rest, Msgs, CP, Io>
    SyncHandshake<N, Initiator, Cons<Message<ToResponder, Tokens>, Rest>, Msgs, CP, Io>
where
    N: Protocol,
    CP: CryptoProvider<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Provide our local static key (`-> s`).
    pub fn set_s(
        mut self,
        static_key: CP::PrivateKey,
    ) -> Result<SyncHandshake<N, Initiator, Rest, Msgs, CP, Io>, HandshakeError> {
        let s_pub = self
            .inner
            .provider
            .public_key(&static_key)
            .map_err(|e| HandshakeError::Crypto(e.to_string()))?;
        self.inner.symmetric.mix_hash(s_pub.as_ref());
        self.inner.s_pub = Some(s_pub);
        self.inner.s = Some(static_key);
        Ok(SyncHandshake {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        })
    }
}

// `-> s` + Responder: the initiator's static is the remote static.
impl<N, Tokens, Rest, Msgs, CP, Io>
    SyncHandshake<N, Responder, Cons<Message<ToResponder, Tokens>, Rest>, Msgs, CP, Io>
where
    N: Protocol,
    CP: CryptoProvider<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Provide the remote party's static public key (`-> s`).
    pub fn set_rs(
        mut self,
        remote_static: <N::Curve as Curve>::PublicKey,
    ) -> SyncHandshake<N, Responder, Rest, Msgs, CP, Io> {
        self.inner.symmetric.mix_hash(remote_static.as_ref());
        self.inner.rs = Some(remote_static);
        SyncHandshake {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        }
    }
}

// ═══════════════════════════════════════════════════════════════
//  Entry points: HandshakeState → Sending / Receiving
// ═══════════════════════════════════════════════════════════════

// Start a send message whose first token is E.
impl<N, R, Tokens, MsgRest, Dir, CP, Io>
    SyncHandshake<N, R, Nil, Cons<Message<Dir, Cons<E, Tokens>>, MsgRest>, CP, Io>
where
    N: Protocol,
    R: Role<SendDir = Dir>,
    CP: CryptoProvider<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
    Io: Write,
{
    /// Generate and stream our ephemeral public key (`e`).
    pub fn e(mut self) -> Result<SyncSending<N, R, Tokens, MsgRest, CP, Io>, HandshakeError> {
        sync_stream_e(&mut self.inner, &mut self.stream)?;
        Ok(SyncSending {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        })
    }
}

// Start a send message whose first token is Psk.
impl<N, R, Tokens, MsgRest, Dir, CP, Io>
    SyncHandshake<N, R, Nil, Cons<Message<Dir, Cons<Psk, Tokens>>, MsgRest>, CP, Io>
where
    N: Protocol,
    R: Role<SendDir = Dir>,
    CP: CryptoProvider<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
{
    /// Mix the pre-shared key (`psk`) — writes nothing to the wire.
    pub fn psk(
        mut self,
        psk_key: &crate::psk::Psk,
    ) -> Result<SyncSending<N, R, Tokens, MsgRest, CP, Io>, HandshakeError> {
        do_psk(&mut self.inner, psk_key)?;
        Ok(SyncSending {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        })
    }
}

// Start a send message whose first token is S.
impl<N, R, Tokens, MsgRest, Dir, CP, Io>
    SyncHandshake<N, R, Nil, Cons<Message<Dir, Cons<S, Tokens>>, MsgRest>, CP, Io>
where
    N: Protocol,
    R: Role<SendDir = Dir>,
    CP: CryptoProvider<N::Curve>,
    <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
    Io: Write,
{
    /// Encrypt and stream our static public key (`s`).
    pub fn s(
        mut self,
        static_key: CP::PrivateKey,
    ) -> Result<SyncSending<N, R, Tokens, MsgRest, CP, Io>, HandshakeError> {
        sync_stream_s(&mut self.inner, &mut self.stream, static_key)?;
        Ok(SyncSending {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        })
    }
}

// Start receiving the next message (PreMsgs = Nil, message is ours to
// read). No bytes are read here — each token pulls exactly what it needs.
impl<N, R, Tokens, Rest, Dir, CP, Io>
    SyncHandshake<N, R, Nil, Cons<Message<Dir, Tokens>, Rest>, CP, Io>
where
    N: Protocol,
    R: Role<RecvDir = Dir>,
    CP: CryptoProvider<N::Curve>,
{
    /// Begin reading the next incoming handshake message.
    pub fn recv(self) -> SyncReceiving<N, R, Tokens, Rest, CP, Io> {
        SyncReceiving {
            inner: self.inner,
            stream: self.stream,
            _marker: PhantomData,
        }
    }
}

// ═══════════════════════════════════════════════════════════════
//  Macro: three-variant impls for a send token
// ═══════════════════════════════════════════════════════════════

/// Generate three `impl` blocks for a send-side token method. The body
/// has access to `inner: &mut HandshakeInner` and `stream: &mut Io`
/// (name it `_stream` for DH/psk tokens that write nothing) plus any
/// declared args.
macro_rules! sync_send_token {
    (
        role: $R:ty,
        token: $Token:ty,
        method: $method:ident ($($arg:ident : $arg_ty:ty),*),
        bounds: [$($extra:tt)*],
        body: |$inner:ident, $stream:ident| { $($logic:tt)* }
    ) => {
        // Variant 1: more tokens after this one.
        impl<N, Next, More, MsgRest, CP, Io>
            SyncSending<N, $R, Cons<$Token, Cons<Next, More>>, MsgRest, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProvider<N::Curve>,
            Io: Write,
            $($extra)*
        {
            pub fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<SyncSending<N, $R, Cons<Next, More>, MsgRest, CP, Io>, HandshakeError> {
                {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                }
                Ok(SyncSending { inner: self.inner, stream: self.stream, _marker: PhantomData })
            }
        }

        // Variant 2: last token, more messages.
        impl<N, NextMsg, MoreMsgs, CP, Io>
            SyncSending<N, $R, Cons<$Token, Nil>, Cons<NextMsg, MoreMsgs>, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProvider<N::Curve>,
            Io: Write,
            $($extra)*
        {
            pub fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<SyncHandshake<N, $R, Nil, Cons<NextMsg, MoreMsgs>, CP, Io>, HandshakeError> {
                {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                }
                send_message_tail(&mut self.inner, &mut self.stream)?;
                Ok(SyncHandshake { inner: self.inner, stream: self.stream, _marker: PhantomData })
            }
        }

        // Variant 3: last token, last message.
        impl<N, CP, Io>
            SyncSending<N, $R, Cons<$Token, Nil>, Nil, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProvider<N::Curve>,
            Io: Write,
            $($extra)*
        {
            pub fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<SyncTransport<N, Io>, HandshakeError> {
                {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                }
                send_message_tail(&mut self.inner, &mut self.stream)?;
                let transport = recv_to_transport::<N, $R, CP>(self.inner);
                Ok(SyncTransport { transport, stream: self.stream })
            }
        }
    };
}

// ═══════════════════════════════════════════════════════════════
//  Macro: three-variant impls for a recv token (no revealed key)
// ═══════════════════════════════════════════════════════════════

macro_rules! sync_recv_token {
    (
        role: $R:ty,
        token: $Token:ty,
        method: $method:ident ($($arg:ident : $arg_ty:ty),*),
        bounds: [$($extra:tt)*],
        body: |$inner:ident, $stream:ident| { $($logic:tt)* }
    ) => {
        // Variant 1: more tokens.
        impl<N, Next, More, MsgRest, CP, Io>
            SyncReceiving<N, $R, Cons<$Token, Cons<Next, More>>, MsgRest, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProvider<N::Curve>,
            Io: Read,
            $($extra)*
        {
            pub fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<SyncReceiving<N, $R, Cons<Next, More>, MsgRest, CP, Io>, HandshakeError> {
                {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                }
                Ok(SyncReceiving { inner: self.inner, stream: self.stream, _marker: PhantomData })
            }
        }

        // Variant 2: last token, more messages.
        impl<N, NextMsg, MoreMsgs, CP, Io>
            SyncReceiving<N, $R, Cons<$Token, Nil>, Cons<NextMsg, MoreMsgs>, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProvider<N::Curve>,
            Io: Read,
            $($extra)*
        {
            pub fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<SyncHandshake<N, $R, Nil, Cons<NextMsg, MoreMsgs>, CP, Io>, HandshakeError> {
                {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                }
                recv_message_tail(&mut self.inner, &mut self.stream)?;
                Ok(SyncHandshake { inner: self.inner, stream: self.stream, _marker: PhantomData })
            }
        }

        // Variant 3: last token, last message.
        impl<N, CP, Io>
            SyncReceiving<N, $R, Cons<$Token, Nil>, Nil, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProvider<N::Curve>,
            Io: Read,
            $($extra)*
        {
            pub fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<SyncTransport<N, Io>, HandshakeError> {
                {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                }
                recv_message_tail(&mut self.inner, &mut self.stream)?;
                let transport = recv_to_transport::<N, $R, CP>(self.inner);
                Ok(SyncTransport { transport, stream: self.stream })
            }
        }
    };
}

// ═══════════════════════════════════════════════════════════════
//  Macro: recv token that reveals a public key (E or S)
// ═══════════════════════════════════════════════════════════════

macro_rules! sync_recv_reveal_token {
    (
        role: $R:ty,
        token: $Token:ty,
        method: $method:ident ($($arg:ident : $arg_ty:ty),*),
        bounds: [$($extra:tt)*],
        body: |$inner:ident, $stream:ident| { $($logic:tt)* }
    ) => {
        // Variant 1: more tokens after this one.
        impl<N, Next, More, MsgRest, CP, Io>
            SyncReceiving<N, $R, Cons<$Token, Cons<Next, More>>, MsgRest, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProvider<N::Curve>,
            Io: Read,
            $($extra)*
        {
            #[allow(clippy::type_complexity)]
            pub fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<(<N::Curve as Curve>::PublicKey, SyncReceiving<N, $R, Cons<Next, More>, MsgRest, CP, Io>), HandshakeError> {
                let revealed = {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                };
                Ok((revealed, SyncReceiving { inner: self.inner, stream: self.stream, _marker: PhantomData }))
            }
        }

        // Variant 2: last token, more messages.
        impl<N, NextMsg, MoreMsgs, CP, Io>
            SyncReceiving<N, $R, Cons<$Token, Nil>, Cons<NextMsg, MoreMsgs>, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProvider<N::Curve>,
            Io: Read,
            $($extra)*
        {
            #[allow(clippy::type_complexity)]
            pub fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<(<N::Curve as Curve>::PublicKey, SyncHandshake<N, $R, Nil, Cons<NextMsg, MoreMsgs>, CP, Io>), HandshakeError> {
                let revealed = {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                };
                recv_message_tail(&mut self.inner, &mut self.stream)?;
                Ok((revealed, SyncHandshake { inner: self.inner, stream: self.stream, _marker: PhantomData }))
            }
        }

        // Variant 3: last token, last message.
        impl<N, CP, Io>
            SyncReceiving<N, $R, Cons<$Token, Nil>, Nil, CP, Io>
        where
            N: Protocol,
            <N::Curve as Curve>::PublicKey: AsRef<[u8]>,
            CP: CryptoProvider<N::Curve>,
            Io: Read,
            $($extra)*
        {
            #[allow(clippy::type_complexity)]
            pub fn $method(
                mut self, $($arg: $arg_ty,)*
            ) -> Result<(<N::Curve as Curve>::PublicKey, SyncTransport<N, Io>), HandshakeError> {
                let revealed = {
                    let $inner = &mut self.inner;
                    let $stream = &mut self.stream;
                    $($logic)*
                };
                recv_message_tail(&mut self.inner, &mut self.stream)?;
                let transport = recv_to_transport::<N, $R, CP>(self.inner);
                Ok((revealed, SyncTransport { transport, stream: self.stream }))
            }
        }
    };
}

// ═══════════════════════════════════════════════════════════════
//  Token: E (role-independent)
// ═══════════════════════════════════════════════════════════════

sync_send_token! {
    role: Initiator, token: E, method: e(), bounds: [],
    body: |inner, stream| { sync_stream_e(inner, stream)?; }
}
sync_send_token! {
    role: Responder, token: E, method: e(), bounds: [],
    body: |inner, stream| { sync_stream_e(inner, stream)?; }
}
sync_recv_reveal_token! {
    role: Initiator, token: E, method: e(), bounds: [],
    body: |inner, stream| { sync_read_e(inner, stream)? }
}
sync_recv_reveal_token! {
    role: Responder, token: E, method: e(), bounds: [],
    body: |inner, stream| { sync_read_e(inner, stream)? }
}

// ═══════════════════════════════════════════════════════════════
//  Token: S
// ═══════════════════════════════════════════════════════════════

sync_send_token! {
    role: Initiator, token: S, method: s(static_key: CP::PrivateKey), bounds: [],
    body: |inner, stream| { sync_stream_s(inner, stream, static_key)?; }
}
sync_send_token! {
    role: Responder, token: S, method: s(static_key: CP::PrivateKey), bounds: [],
    body: |inner, stream| { sync_stream_s(inner, stream, static_key)?; }
}
sync_recv_reveal_token! {
    role: Initiator, token: S, method: s(), bounds: [],
    body: |inner, stream| { sync_read_s(inner, stream)? }
}
sync_recv_reveal_token! {
    role: Responder, token: S, method: s(), bounds: [],
    body: |inner, stream| { sync_read_s(inner, stream)? }
}

// ═══════════════════════════════════════════════════════════════
//  Token: Ee (role-independent)
// ═══════════════════════════════════════════════════════════════

sync_send_token! {
    role: Initiator, token: Ee, method: ee(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_ee(inner)?; }
}
sync_send_token! {
    role: Responder, token: Ee, method: ee(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_ee(inner)?; }
}
sync_recv_token! {
    role: Initiator, token: Ee, method: ee(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_ee(inner)?; }
}
sync_recv_token! {
    role: Responder, token: Ee, method: ee(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_ee(inner)?; }
}

// ═══════════════════════════════════════════════════════════════
//  Token: Es (role-dependent)
// ═══════════════════════════════════════════════════════════════

sync_send_token! {
    role: Initiator, token: Es, method: es(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_es_initiator(inner)?; }
}
sync_recv_token! {
    role: Initiator, token: Es, method: es(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_es_initiator(inner)?; }
}
sync_send_token! {
    role: Responder, token: Es, method: es(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_es_responder(inner)?; }
}
sync_recv_token! {
    role: Responder, token: Es, method: es(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_es_responder(inner)?; }
}

// ═══════════════════════════════════════════════════════════════
//  Token: Se (role-dependent)
// ═══════════════════════════════════════════════════════════════

sync_send_token! {
    role: Initiator, token: Se, method: se(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_se_initiator(inner)?; }
}
sync_recv_token! {
    role: Initiator, token: Se, method: se(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_se_initiator(inner)?; }
}
sync_send_token! {
    role: Responder, token: Se, method: se(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_se_responder(inner)?; }
}
sync_recv_token! {
    role: Responder, token: Se, method: se(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_se_responder(inner)?; }
}

// ═══════════════════════════════════════════════════════════════
//  Token: Ss (role-independent)
// ═══════════════════════════════════════════════════════════════

sync_send_token! {
    role: Initiator, token: Ss, method: ss(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_ss(inner)?; }
}
sync_send_token! {
    role: Responder, token: Ss, method: ss(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_ss(inner)?; }
}
sync_recv_token! {
    role: Initiator, token: Ss, method: ss(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_ss(inner)?; }
}
sync_recv_token! {
    role: Responder, token: Ss, method: ss(), bounds: [<N::Curve as Curve>::SharedSecret: AsRef<[u8]>,],
    body: |inner, _stream| { sync_do_ss(inner)?; }
}

// ═══════════════════════════════════════════════════════════════
//  Token: Psk (role-independent)
// ═══════════════════════════════════════════════════════════════

sync_send_token! {
    role: Initiator, token: Psk, method: psk(psk_key: &crate::psk::Psk), bounds: [],
    body: |inner, _stream| { do_psk(inner, psk_key)?; }
}
sync_send_token! {
    role: Responder, token: Psk, method: psk(psk_key: &crate::psk::Psk), bounds: [],
    body: |inner, _stream| { do_psk(inner, psk_key)?; }
}
sync_recv_token! {
    role: Initiator, token: Psk, method: psk(psk_key: &crate::psk::Psk), bounds: [],
    body: |inner, _stream| { do_psk(inner, psk_key)?; }
}
sync_recv_token! {
    role: Responder, token: Psk, method: psk(psk_key: &crate::psk::Psk), bounds: [],
    body: |inner, _stream| { do_psk(inner, psk_key)?; }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::curve::p256::SoftwareCryptoProvider;
    use crate::curve::{CryptoKeys, CryptoProvider};
    use crate::noise::{Blake2b, ChaChaPoly, IKpsk1, Initiator, K, N, Noise, P256, Responder};
    use crate::noise_message_size;
    use crate::psk::Psk;
    use std::cell::RefCell;
    use std::collections::VecDeque;
    use std::io::Cursor;
    use std::rc::Rc;

    type Seal = Noise<N, P256, ChaChaPoly, Blake2b>;
    type Channel = Noise<IKpsk1, P256, ChaChaPoly, Blake2b>;
    type NoiseK = Noise<K, P256, ChaChaPoly, Blake2b>;

    /// A single-threaded in-memory bidirectional byte pipe. Reads pull
    /// from one shared queue, writes push to the other; the peer endpoint
    /// has them swapped. Safe to drive ping-pong on one thread (each side
    /// finishes a message's I/O before yielding), so no blocking/deadlock.
    #[derive(Clone)]
    struct Pipe {
        inbound: Rc<RefCell<VecDeque<u8>>>,
        outbound: Rc<RefCell<VecDeque<u8>>>,
    }

    impl std::io::Read for Pipe {
        fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
            let mut q = self.inbound.borrow_mut();
            let n = q.len().min(buf.len());
            for slot in buf.iter_mut().take(n) {
                *slot = q.pop_front().unwrap();
            }
            Ok(n)
        }
    }

    impl std::io::Write for Pipe {
        fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
            self.outbound.borrow_mut().extend(buf.iter().copied());
            Ok(buf.len())
        }
        fn flush(&mut self) -> std::io::Result<()> {
            Ok(())
        }
    }

    /// Full Noise N seal/open over blocking `std::io`, with a real
    /// transport round-trip — proves wire correctness end-to-end (any
    /// wrong byte would break the AEAD tag).
    #[test]
    fn n_sync_seal_open_roundtrip() {
        let provider = SoftwareCryptoProvider;
        let recipient_static = provider.generate_static_key().unwrap();
        let recipient_pub = provider.public_key(&recipient_static).unwrap();

        // ── Seal (initiator) — stream into an owned Vec ──────────────
        let sealer = SyncHandshake::<Seal, Initiator, _, _, _, _>::initiate(
            SoftwareCryptoProvider,
            &[],
            Vec::<u8>::new(),
        )
        .set_rs(recipient_pub);
        let sealer_done = sealer.e().unwrap().es().unwrap();
        let (mut send_transport, wire) = sealer_done.into_parts();
        // msg1 = ephemeral (65) + empty-payload tag (16) = 81 bytes.
        assert_eq!(wire.len(), 81);

        let payload = [0x42u8; 32];
        let mut sealed = [0u8; 48];
        let sealed_len = send_transport.send(&payload, &mut sealed).unwrap();

        // ── Open (responder) — read from a Cursor over the wire ──────
        let opener = SyncHandshake::<Seal, Responder, _, _, _, _>::respond(
            SoftwareCryptoProvider,
            &[],
            Cursor::new(wire),
        )
        .set_s(recipient_static)
        .unwrap();
        let (_revealed_e, recv) = opener.recv().e().unwrap();
        let mut recv_transport = recv.es().unwrap();

        // Both sides derived the same session.
        assert_eq!(
            send_transport.session_id(),
            recv_transport.transport().session_id()
        );

        let mut opened = [0u8; 32];
        let opened_len = recv_transport
            .transport()
            .receive(&sealed[..sealed_len], &mut opened)
            .unwrap();
        assert_eq!(opened_len, 32);
        assert_eq!(opened, payload);
    }

    /// A corrupted ephemeral on the wire must make the responder's `es`
    /// fail (DH mismatch → payload-tag verification fails).
    #[test]
    fn n_sync_tampered_ephemeral_rejected() {
        let provider = SoftwareCryptoProvider;
        let recipient_static = provider.generate_static_key().unwrap();
        let recipient_pub = provider.public_key(&recipient_static).unwrap();

        let sealer = SyncHandshake::<Seal, Initiator, _, _, _, _>::initiate(
            SoftwareCryptoProvider,
            &[],
            Vec::<u8>::new(),
        )
        .set_rs(recipient_pub);
        let (_t, mut wire) = sealer.e().unwrap().es().unwrap().into_parts();
        wire[1] ^= 0xFF; // flip a byte in the ephemeral public key

        let opener = SyncHandshake::<Seal, Responder, _, _, _, _>::respond(
            SoftwareCryptoProvider,
            &[],
            Cursor::new(wire),
        )
        .set_s(recipient_static)
        .unwrap();

        // The `e` read may already reject an invalid point; otherwise the
        // DH mismatch surfaces at `es` (payload-tag failure).
        match opener.recv().e() {
            Err(_) => {}
            Ok((_e, recv)) => assert!(recv.es().is_err()),
        }
    }

    /// The same blocking handshake works with the **Secure Enclave**
    /// provider — proving Apple keys are usable synchronously (using
    /// software-backed `SecKey`s so the test needs no SE hardware).
    #[cfg(any(target_os = "macos", target_os = "ios"))]
    #[test]
    fn n_sync_seal_open_with_secure_enclave_provider() {
        use crate::curve::p256::SecureEnclaveCryptoProvider;

        let provider = SecureEnclaveCryptoProvider;
        let recipient_static = provider.generate_ephemeral_key().unwrap();
        let recipient_pub = provider.public_key(&recipient_static).unwrap();

        let sealer = SyncHandshake::<Seal, Initiator, _, _, _, _>::initiate(
            SecureEnclaveCryptoProvider,
            &[],
            Vec::<u8>::new(),
        )
        .set_rs(recipient_pub);
        let (mut send_transport, wire) = sealer.e().unwrap().es().unwrap().into_parts();
        assert_eq!(wire.len(), 81);

        let payload = [0x42u8; 32];
        let mut sealed = [0u8; 48];
        let sealed_len = send_transport.send(&payload, &mut sealed).unwrap();

        let opener = SyncHandshake::<Seal, Responder, _, _, _, _>::respond(
            SecureEnclaveCryptoProvider,
            &[],
            Cursor::new(wire),
        )
        .set_s(recipient_static)
        .unwrap();
        let (_revealed_e, recv) = opener.recv().e().unwrap();
        let mut recv_transport = recv.es().unwrap();

        assert_eq!(
            send_transport.session_id(),
            recv_transport.transport().session_id()
        );
        let mut opened = [0u8; 32];
        let opened_len = recv_transport
            .transport()
            .receive(&sealed[..sealed_len], &mut opened)
            .unwrap();
        assert_eq!(&opened[..opened_len], &payload);
    }

    /// **Cross-check against the snow-verified buffer core.** A full
    /// IKpsk1 handshake (`-> e,es,s,ss,psk` / `<- e,ee,se` — every token,
    /// both messages) driven with the blocking `io_sync` **initiator**
    /// against the async buffer-core **responder**. The buffer core is
    /// the snow-interop-verified path, so any divergence (a swapped DH
    /// role, a wrong byte count, a missed mix) surfaces as a tag failure
    /// here. This anchors `io_sync`'s initiator-role helpers to snow.
    #[tokio::test]
    async fn ikpsk1_sync_initiator_vs_buffer_core() {
        let provider = SoftwareCryptoProvider;
        let initiator_static = provider.generate_static_key().unwrap();
        let initiator_pub = provider.public_key(&initiator_static).unwrap();
        let responder_static = provider.generate_static_key().unwrap();
        let responder_pub = provider.public_key(&responder_static).unwrap();
        let psk = Psk::from_bytes([0xAA; 32]);

        let (i2r, r2i) = (
            Rc::new(RefCell::new(VecDeque::<u8>::new())),
            Rc::new(RefCell::new(VecDeque::<u8>::new())),
        );
        let init_stream = Pipe {
            inbound: r2i.clone(),
            outbound: i2r.clone(),
        };

        // io_sync initiator drives msg1 (-> e, es, s, ss, psk).
        let i_hs = SyncHandshake::<Channel, Initiator, _, _, _, _>::initiate(
            SoftwareCryptoProvider,
            &[],
            init_stream,
        )
        .set_rs(responder_pub);
        let i_hs = i_hs
            .e()
            .unwrap()
            .es()
            .unwrap()
            .s(initiator_static)
            .unwrap()
            .ss()
            .unwrap()
            .psk(&psk)
            .unwrap();
        let msg1: Vec<u8> = i2r.borrow_mut().drain(..).collect();
        assert_eq!(msg1.len(), 162);

        // buffer-core responder consumes msg1 and produces msg2.
        let r_hs = Channel::respond(SoftwareCryptoProvider, &[])
            .set_s(responder_static)
            .unwrap();
        let (_revealed_i_e, recv) = r_hs.read(&msg1).unwrap().e().await.unwrap();
        let recv = recv.es().await.unwrap();
        let (revealed_i_pub, recv) = recv.s().await.unwrap();
        assert_eq!(revealed_i_pub, initiator_pub);
        let recv = recv.ss().await.unwrap();
        let r_hs = recv.psk(&psk).await.unwrap();

        let mut msg2_buf = [0u8;
            noise_message_size!(curve: P256, cipher: ChaChaPoly, has_psk: true, keyed: true, tokens: [E, Ee, Se],)];
        let (msg2, r_transport) = r_hs
            .e(&mut msg2_buf)
            .await
            .unwrap()
            .ee()
            .await
            .unwrap()
            .se()
            .await
            .unwrap();
        r2i.borrow_mut().extend(msg2.iter().copied());

        // io_sync initiator consumes msg2 (<- e, ee, se).
        let (_revealed_r_e, recv) = i_hs.recv().e().unwrap();
        let i_transport = recv.ee().unwrap().se().unwrap();

        // Both ends derived the same session.
        assert_eq!(i_transport.transport.session_id(), r_transport.session_id());
    }

    /// Mirror of the above with roles flipped: blocking `io_sync`
    /// **responder** against the async buffer-core **initiator** — anchors
    /// `io_sync`'s responder-role helpers (`es`/`se`/`ss` responder DH,
    /// `recv_s`, the `e`/`ee`/`se` send path) to the snow-verified core.
    #[tokio::test]
    async fn ikpsk1_sync_responder_vs_buffer_core() {
        let provider = SoftwareCryptoProvider;
        let initiator_static = provider.generate_static_key().unwrap();
        let initiator_pub = provider.public_key(&initiator_static).unwrap();
        let responder_static = provider.generate_static_key().unwrap();
        let responder_pub = provider.public_key(&responder_static).unwrap();
        let psk = Psk::from_bytes([0xBB; 32]);

        // buffer-core initiator builds msg1.
        let i_hs = Channel::initiate(SoftwareCryptoProvider, &[]).set_rs(responder_pub);
        let mut msg1_buf = [0u8;
            noise_message_size!(curve: P256, cipher: ChaChaPoly, has_psk: true, keyed: false, tokens: [E, Es, S, Ss, Psk],)];
        let (msg1, i_hs) = i_hs
            .e(&mut msg1_buf)
            .await
            .unwrap()
            .es()
            .await
            .unwrap()
            .s(initiator_static)
            .await
            .unwrap()
            .ss()
            .await
            .unwrap()
            .psk(&psk)
            .await
            .unwrap();
        let msg1 = msg1.to_vec();

        // io_sync responder consumes msg1 and produces msg2.
        let (i2r, r2i) = (
            Rc::new(RefCell::new(VecDeque::<u8>::new())),
            Rc::new(RefCell::new(VecDeque::<u8>::new())),
        );
        i2r.borrow_mut().extend(msg1.iter().copied());
        let resp_stream = Pipe {
            inbound: i2r.clone(),
            outbound: r2i.clone(),
        };
        let r_hs = SyncHandshake::<Channel, Responder, _, _, _, _>::respond(
            SoftwareCryptoProvider,
            &[],
            resp_stream,
        )
        .set_s(responder_static)
        .unwrap();
        let (_e, recv) = r_hs.recv().e().unwrap();
        let recv = recv.es().unwrap();
        let (revealed_i_pub, recv) = recv.s().unwrap();
        assert_eq!(revealed_i_pub, initiator_pub);
        let recv = recv.ss().unwrap();
        // psk is msg1's last token with msg2 still pending → back to a
        // SyncHandshake; the responder's next message is outgoing.
        let r_hs = recv.psk(&psk).unwrap();
        let r_transport = r_hs.e().unwrap().ee().unwrap().se().unwrap();
        let msg2: Vec<u8> = r2i.borrow_mut().drain(..).collect();
        assert_eq!(msg2.len(), 81);

        // buffer-core initiator consumes msg2 (<- e, ee, se).
        let (_re, recv) = i_hs.read(&msg2).unwrap().e().await.unwrap();
        let i_transport = recv.ee().await.unwrap().se().await.unwrap();

        // Both ends derived the same session.
        assert_eq!(i_transport.session_id(), r_transport.transport.session_id());
    }

    /// Noise K (`-> e, es, ss`, pre `-> s, <- s`) round-trip over blocking
    /// `std::io` — single-message, exercises the `-> s` pre-message
    /// setters and the `ss` token end-to-end.
    #[test]
    fn k_sync_round_trip() {
        let provider = SoftwareCryptoProvider;
        let alice_static = provider.generate_static_key().unwrap();
        let alice_pub = provider.public_key(&alice_static).unwrap();
        let bob_static = provider.generate_static_key().unwrap();
        let bob_pub = provider.public_key(&bob_static).unwrap();
        let payload = [0x42u8; 32];

        // initiator: pre -> s (alice), <- s (bob); msg1 -> e, es, ss.
        let sealer = SyncHandshake::<NoiseK, Initiator, _, _, _, _>::initiate(
            SoftwareCryptoProvider,
            &[],
            Vec::<u8>::new(),
        )
        .set_s(alice_static)
        .unwrap()
        .set_rs(bob_pub);
        let (mut send_transport, wire) =
            sealer.e().unwrap().es().unwrap().ss().unwrap().into_parts();
        assert_eq!(wire.len(), 81);
        let mut sealed = [0u8; 48];
        let n = send_transport.send(&payload, &mut sealed).unwrap();

        // responder: pre -> s (alice via set_rs), <- s (bob via set_s).
        let opener = SyncHandshake::<NoiseK, Responder, _, _, _, _>::respond(
            SoftwareCryptoProvider,
            &[],
            Cursor::new(wire),
        )
        .set_rs(alice_pub)
        .set_s(bob_static)
        .unwrap();
        let (_e, recv) = opener.recv().e().unwrap();
        let mut recv_transport = recv.es().unwrap().ss().unwrap();
        assert_eq!(
            send_transport.session_id(),
            recv_transport.transport().session_id()
        );
        let mut opened = [0u8; 32];
        let on = recv_transport
            .transport()
            .receive(&sealed[..n], &mut opened)
            .unwrap();
        assert_eq!(&opened[..on], &payload);
    }
}
