//! An IKpsk1-shaped enrolment ceremony over a real localhost TCP socket,
//! driven by a handshake **generated by the `noise!` macro** — no I/O
//! driver, no async runtime, no buffer sizing: every handshake message is
//! a fixed-size byte array and the "driver" is a plain `write_all` /
//! `read_exact` pair the caller owns.
//!
//! Run with:
//!
//! ```text
//! cargo run --example tcp_ikpsk1_ceremony
//! ```
//!
//! # The pattern
//!
//! The macro takes the pattern in the Noise specification's own notation.
//! We name the type `IKpsk1`, after the pattern it spells, because the name
//! is part of the protocol identity: it becomes
//! `Noise_IKpsk1_25519_ChaChaPoly_BLAKE2b`, which seeds every transcript,
//! so only peers speaking *exactly* this protocol — same name, same suite,
//! same tokens — can complete the handshake. Naming it anything else would
//! still work between two hiss peers and interoperate with nothing. The
//! role the channel plays in this example goes on a `type Ceremony`
//! alias, which is what the code below reads from. The token sequence:
//!
//! ```text
//! IKpsk1:
//!   <- s                      (the device already knows the server's static key)
//!   ...
//!   -> e, es, s, ss, psk      (msg1: the device proves who it is, under PSK)
//!   <- e, ee, se              (msg2: the server authenticates back)
//! ```
//!
//! Everything below the `noise!` invocation is ordinary socket code: the
//! generated states expose `Ceremony::MSG1_SIZE` / `Ceremony::MSG2_SIZE`,
//! so each side reads exactly the bytes the pattern prescribes — framing
//! for the *handshake* is free. (Transport records are variable-length,
//! so those get a 2-byte length prefix, as in any Noise application.)

use std::io::{Read, Write};
use std::net::{TcpListener, TcpStream};

use hiss::curve::Curve;
use hiss::noise::{Blake2b, ChaChaPoly, HandshakeError, Transport, X25519};
use hiss::provider::{CryptoKeyProvider, EphemeralOnly, ProviderExt};
use hiss::psk::Psk;

use rand::rngs::StdRng;

type BoxError = Box<dyn std::error::Error + Send + Sync>;

hiss::noise! {
    /// `IKpsk1` over X25519 / ChaChaPoly / BLAKE2b.
    pub IKpsk1<X25519, ChaChaPoly, Blake2b> {
        <- s
        ...
        -> e, es, s, ss, psk
        <- e, ee, se
    }
}

/// What the channel is *for* in this example. The protocol name on the
/// wire stays `IKpsk1`; the role lives on the alias.
type Ceremony = IKpsk1;

/// The software crypto backend both sides run on in this example.
type Provider = EphemeralOnly<StdRng>;
/// An X25519 static private key as this provider represents it.
type StaticKey = <Provider as CryptoKeyProvider<X25519>>::PrivateKey;
/// An X25519 public key.
type PublicKey = <X25519 as Curve>::PublicKey;

const PROLOGUE: &[u8] = b"ceremony-example-v1";
const OVERHEAD: usize = Transport::<Ceremony>::OVERHEAD;

fn main() -> Result<(), BoxError> {
    // ── Out-of-band setup ────────────────────────────────────────
    // The server's static key pair; its *public* half is pre-shared with
    // the device (Ceremony's `<- s` pre-message). The per-device PSK was
    // established at enrolment time.
    let mut server_provider = Provider::new(rand::make_rng::<StdRng>());
    let server_static = server_provider.generate::<X25519>()?;
    let server_pub = server_provider.public(&server_static)?;

    let mut device_provider = Provider::new(rand::make_rng::<StdRng>());
    let device_static = device_provider.generate::<X25519>()?;
    let device_pub = device_provider.public(&device_static)?;

    let psk = Psk::from_bytes([0x42; 32]);

    // ── Wire ─────────────────────────────────────────────────────
    let listener = TcpListener::bind("127.0.0.1:0")?;
    let addr = listener.local_addr()?;

    let server_psk = psk.clone();
    let server = std::thread::spawn(move || {
        server_side(
            listener,
            server_provider,
            server_static,
            server_psk,
            device_pub,
        )
    });

    let stream = TcpStream::connect(addr)?;
    let (device_sid, reply) =
        device_side(stream, device_provider, device_static, server_pub, &psk)?;
    let (server_sid, hello) = server.join().expect("server thread")?;

    // Channel binding: both ends derived the same session id (the
    // handshake transcript hash) — the handshakes were byte-identical.
    assert_eq!(device_sid, server_sid, "session ids must match");

    println!("ceremony complete");
    println!("session id (hex): {device_sid}");
    println!("server decrypted: {hello:?}");
    println!("device decrypted: {reply:?}");
    Ok(())
}

/// The **device** (initiator): sends msg1, reads msg2, then talks.
fn device_side(
    mut stream: TcpStream,
    provider: Provider,
    device_static: StaticKey,
    server_pub: PublicKey,
    psk: &Psk,
) -> Result<(String, String), BoxError> {
    // msg1: -> e, es, s, ss, psk — one call, built entirely in memory…
    let hs = Ceremony::initiator(provider, PROLOGUE, server_pub);
    let (msg1, hs) = hs.write_message_1(device_static, psk)?;

    // …and this is the whole "driver": one write, one read.
    stream.write_all(&msg1)?;
    let mut msg2 = [0u8; Ceremony::MSG2_SIZE];
    stream.read_exact(&mut msg2)?;

    // msg2: <- e, ee, se — one call, completing into the transport keys.
    let mut transport = hs.read_message_2(&msg2)?;
    let session_id = transport.session_id().to_string();

    // Transport phase: records are variable-length, so length-prefix them.
    let hello = b"hello from the device";
    let mut sealed = vec![0u8; hello.len() + OVERHEAD];
    let n = transport.send(hello, &mut sealed)?;
    write_frame(&mut stream, &sealed[..n])?;

    let frame = read_frame(&mut stream)?;
    let mut opened = vec![0u8; frame.len()];
    let n = transport.receive(&frame, &mut opened)?;
    opened.truncate(n);

    Ok((session_id, String::from_utf8(opened)?))
}

/// The **server** (responder): reads msg1 — learning, and verifying, the
/// device's identity — answers with msg2, then talks.
fn server_side(
    listener: TcpListener,
    provider: Provider,
    server_static: StaticKey,
    psk: Psk,
    expected_device: PublicKey,
) -> Result<(String, String), BoxError> {
    let (mut stream, _peer) = listener.accept()?;

    let hs = Ceremony::responder(provider, PROLOGUE, server_static)?;

    // Read exactly msg1 — the size is a compile-time constant.
    let mut msg1 = [0u8; Ceremony::MSG1_SIZE];
    stream.read_exact(&mut msg1)?;

    // -> e, es, s, ss, psk, in one call. This server holds one PSK per
    // enrolled device, and IKpsk1 reveals the device's identity *before*
    // the psk token precisely to allow that — the `_with` variant hands
    // the identity to a lookup: return the PSK enrolled for it, or
    // reject a stranger and the whole handshake aborts. (A deployment
    // with a single pre-agreed PSK would use `read_message_1(&msg1,
    // &psk)` instead; the identity stays observable either way via
    // `hs.remote_static()`.)
    let hs = hs.read_message_1_with(&msg1, |device| {
        if device.as_ref() == expected_device.as_ref() {
            Ok(psk.clone())
        } else {
            Err(HandshakeError::PeerRejected {
                reason: "no PSK enrolled for this device".into(),
            })
        }
    })?;

    // msg2: <- e, ee, se — one call, one write, and the handshake is done.
    let (msg2, mut transport) = hs.write_message_2()?;
    stream.write_all(&msg2)?;

    let session_id = transport.session_id().to_string();

    // Transport phase: receive the device's record, answer it.
    let frame = read_frame(&mut stream)?;
    let mut opened = vec![0u8; frame.len()];
    let n = transport.receive(&frame, &mut opened)?;
    opened.truncate(n);

    let reply = b"hello back from the server";
    let mut sealed = vec![0u8; reply.len() + OVERHEAD];
    let n = transport.send(reply, &mut sealed)?;
    write_frame(&mut stream, &sealed[..n])?;

    Ok((session_id, String::from_utf8(opened)?))
}

/// Write one transport record with a 2-byte big-endian length prefix.
fn write_frame(stream: &mut TcpStream, payload: &[u8]) -> Result<(), BoxError> {
    let len = u16::try_from(payload.len())?;
    stream.write_all(&len.to_be_bytes())?;
    stream.write_all(payload)?;
    Ok(())
}

/// Read one length-prefixed transport record.
fn read_frame(stream: &mut TcpStream) -> Result<Vec<u8>, BoxError> {
    let mut len_buf = [0u8; 2];
    stream.read_exact(&mut len_buf)?;
    let mut payload = vec![0u8; u16::from_be_bytes(len_buf) as usize];
    stream.read_exact(&mut payload)?;
    Ok(payload)
}
