//! End-to-end Noise **XX** mutual-authentication handshake over a real
//! localhost TCP socket, followed by one encrypted message exchanged in
//! each direction. `hiss` itself does no I/O; the socket work below is
//! ordinary `tokio` code.
//!
//! Run with:
//!
//! ```text
//! cargo run --example tcp_xx_channel
//! ```
//!
//! # The XX pattern
//!
//! XX is the interactive, *mutually-authenticated* handshake in which
//! neither party knows the other's static key in advance — both statics
//! are transmitted (encrypted) **during** the handshake. Its token chain
//! is three messages:
//!
//! ```text
//!   -> e                  (msg1: initiator's ephemeral, in the clear)
//!   <- e, ee, s, es       (msg2: responder's ephemeral, the ee DH,
//!                          then the responder's static — now encrypted —
//!                          and the es DH that authenticates it)
//!   -> s, se              (msg3: initiator's static — encrypted — and
//!                          the se DH that authenticates it)
//! ```
//!
//! After msg3 both ends derive the same transport keys and the same
//! channel-binding `session_id` from the handshake hash.
//!
//! Contrast with the pre-known-static patterns (N, K, IK, XK): there the
//! recipient's static is a *constructor argument*, folded into the
//! transcript before the first byte goes out. **XX's constructors take no
//! keys at all** — there is nothing to pre-set. Instead each side hands its
//! own static *private* key to the write that carries the `s` token, and
//! learns the peer's static *public* key from the read that receives one.
//! That asymmetry — private key in on send, public key out on receive — is
//! the whole shape of XX in this API.
//!
//! **Authentication is only real once you check the peer's static.** XX proves
//! the peer holds *a* static private key, not that you trust it: each side here
//! verifies the revealed key against a small out-of-band trust store and aborts
//! on a stranger.
//!
//! # Framing is free, because every size is a constant
//!
//! `hiss` performs no I/O: each `write_message_N` hands back a fixed-size
//! array and each `read_message_N` takes one. So framing a handshake needs
//! no length prefix — `read_exact` of `Channel::MSGn_SIZE` is the frame.
//! Transport records *are* variable-length, so those keep the 2-byte prefix
//! at the bottom of this file. Swapping the `TcpStream` for an in-memory
//! duplex changes only the two `write_all`/`read_exact` pairs.

use hiss::curve::Curve;
use hiss::noise::{Blake2b, ChaChaPoly, HandshakeError, P256, Transport};
use hiss::provider::{CryptoKeyProvider, EphemeralOnly, ProviderExt};

use rand::{SeedableRng, rngs::StdRng};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::{TcpListener, TcpStream};

type BoxError = Box<dyn std::error::Error + Send + Sync>;

// The protocol this channel runs: `Noise_XX_P256_ChaChaPoly_BLAKE2b`.
//
// The declared identifier *is* the Noise pattern name — it becomes the `XX`
// in the protocol string that seeds the handshake hash — so the generated
// type is `XX`, and `Channel` is the alias that says what it is *for*.
hiss::noise! {
    /// Mutually authenticated channel; neither side pre-knows the other.
    pub XX<P256, ChaChaPoly, Blake2b> {
        -> e
        <- e, ee, s, es
        -> s, se
    }
}
type Channel = XX;

/// A peer's P-256 static public key, as revealed by the completed handshake.
type PublicKey = <P256 as Curve>::PublicKey;

/// A peer's P-256 static private key, as generated by [`EphemeralOnly`].
type StaticKey = <EphemeralOnly<StdRng> as CryptoKeyProvider<P256>>::PrivateKey;

/// A stand-in trust store: the set of peer static public keys we accept.
///
/// A real deployment would consult a pinned allow-list, a certificate store,
/// or an out-of-band enrolment record — the point is that *something* must
/// check the identity XX reveals; `hiss` only proves the peer holds the
/// private half of *a* key, never that the key is one you trust.
fn is_trusted(store: &[PublicKey], peer: &PublicKey) -> bool {
    store.iter().any(|k| k == peer)
}

#[tokio::main]
async fn main() -> Result<(), BoxError> {
    // Bind an ephemeral localhost port and learn the address the OS chose.
    let listener = TcpListener::bind("127.0.0.1:0").await?;
    let addr = listener.local_addr()?;

    // Mint both sides' long-term static identities up front and exchange
    // the public halves out of band — that is what a trust store models
    // for this example; a real deployment would pin these ahead of time
    // rather than mint them fresh. `StdRng` is `Send + Sync`, which the
    // async provider surface and `tokio::spawn` both require; `rand::rng()`
    // (a `!Send` `ThreadRng`) would not cross the task boundary. Seed it
    // from OS entropy.
    let mut init_provider = EphemeralOnly::new(StdRng::from_os_rng());
    let init_static = init_provider.generate::<P256>()?;
    let init_pub = init_provider.public(&init_static)?;

    let mut resp_provider = EphemeralOnly::new(StdRng::from_os_rng());
    let resp_static = resp_provider.generate::<P256>()?;
    let resp_pub = resp_provider.public(&resp_static)?;

    // Spawn the responder. It accepts one connection and drives the XX
    // handshake from the listening end, then echoes its half of the
    // transport exchange. Its final message reports the agreed session id
    // and the plaintext it decrypted, so `main` can cross-check both. Each
    // side's `trusted` list is its out-of-band allow-list of the peer's
    // public static — the responder only trusts `init_pub`, and vice versa.
    let responder = tokio::spawn(responder(
        listener,
        resp_provider,
        resp_static,
        vec![init_pub],
    ));

    // The initiator dials the responder over loopback TCP.
    let initiator = tokio::spawn(initiator(addr, init_provider, init_static, vec![resp_pub]));

    // Join both halves; either side's error (handshake, I/O, or a failed
    // assert) surfaces here.
    let (init_sid, init_decrypted) = initiator.await??;
    let (resp_sid, resp_decrypted) = responder.await??;

    // Channel binding: a completed XX handshake yields the same session id
    // (the handshake hash) on both ends. If these differ, the peers did
    // not share a handshake transcript.
    assert_eq!(
        init_sid, resp_sid,
        "session ids must match (channel binding)"
    );

    println!("handshake complete");
    println!("session id (hex): {init_sid}");
    println!("responder decrypted: {resp_decrypted:?}");
    println!("initiator decrypted: {init_decrypted:?}");

    Ok(())
}

/// Drive the XX handshake and transport exchange as the **initiator**.
///
/// Takes ownership of its provider, its own long-term static key (revealed,
/// encrypted, in msg3), and an allow-list of statics it trusts the responder
/// to present. Returns
/// `(session_id_hex, plaintext_we_decrypted_from_the_responder)`.
async fn initiator(
    addr: std::net::SocketAddr,
    provider: EphemeralOnly<StdRng>,
    my_static: StaticKey,
    trusted: Vec<PublicKey>,
) -> Result<(String, String), BoxError> {
    let mut stream = TcpStream::connect(addr).await?;

    // Begin XX as initiator. XX has no pre-messages, so the constructor
    // takes nothing but the provider and the (here unused) prologue.
    // msg1  -> e          ephemeral only; the cipher is not yet keyed, so
    //                     these bytes go out in the clear.
    let (msg1, hs) = Channel::initiator(provider, &[]).write_message_1()?;
    stream.write_all(&msg1).await?;

    // msg2  <- e, ee, s, es
    //   Read exactly the message's compile-time size, then hand it over.
    //   The `_with` variant runs our trust check the instant the peer's
    //   static decrypts and *before* the message's remaining tokens — so a
    //   stranger is rejected without us ever sending msg3, which is where
    //   we would reveal our own identity.
    let mut msg2 = [0u8; Channel::MSG2_SIZE];
    stream.read_exact(&mut msg2).await?;
    let hs = hs.read_message_2_with(&msg2, |responder_static| {
        if is_trusted(&trusted, responder_static) {
            Ok(())
        } else {
            Err(HandshakeError::PeerRejected {
                reason: "responder static key is not in our trust store".into(),
            })
        }
    })?;

    // msg3  -> s, se
    //   Send our own static (encrypted, authenticated by se). The final
    //   message completes the handshake into the transport state.
    let (msg3, mut transport) = hs.write_message_3(my_static)?;
    stream.write_all(&msg3).await?;

    let session_id = transport.session_id().to_string();

    // Transport phase. Handshake messages were fixed-size, so `read_exact`
    // framed them; transport records are variable-length, so they get a
    // 2-byte big-endian length prefix.
    let plaintext = b"hello from the XX initiator";
    let mut ciphertext = vec![0u8; plaintext.len() + Transport::<Channel>::OVERHEAD];
    let n = transport.send(plaintext, &mut ciphertext)?;
    write_frame(&mut stream, &ciphertext[..n]).await?;

    // Receive the responder's reply and decrypt it.
    let frame = read_frame(&mut stream).await?;
    let mut decrypted = vec![0u8; frame.len()];
    let n = transport.receive(&frame, &mut decrypted)?;
    decrypted.truncate(n);

    Ok((session_id, String::from_utf8(decrypted)?))
}

/// Drive the XX handshake and transport exchange as the **responder**.
///
/// Takes ownership of its provider, its own long-term static key (revealed,
/// encrypted, in msg2), and an allow-list of statics it trusts the initiator
/// to present. Returns
/// `(session_id_hex, plaintext_we_decrypted_from_the_initiator)`.
async fn responder(
    listener: TcpListener,
    provider: EphemeralOnly<StdRng>,
    my_static: StaticKey,
    trusted: Vec<PublicKey>,
) -> Result<(String, String), BoxError> {
    let (mut stream, _peer) = listener.accept().await?;

    // msg1  -> e          read the initiator's ephemeral.
    let mut msg1 = [0u8; Channel::MSG1_SIZE];
    stream.read_exact(&mut msg1).await?;
    let hs = Channel::responder(provider, &[]).read_message_1(&msg1)?;

    // msg2  <- e, ee, s, es
    //   Our ephemeral, the ee DH, then our static — the write takes our
    //   static *private* key and puts the encrypted public half on the
    //   wire. This message starts in the clear (e) and is keyed from ee on.
    let (msg2, hs) = hs.write_message_2(my_static)?;
    stream.write_all(&msg2).await?;

    // msg3  -> s, se
    //   The read reveals the initiator's static; check it against our trust
    //   store before the handshake completes into a transport.
    let mut msg3 = [0u8; Channel::MSG3_SIZE];
    stream.read_exact(&mut msg3).await?;
    let mut transport = hs.read_message_3_with(&msg3, |initiator_static| {
        if is_trusted(&trusted, initiator_static) {
            Ok(())
        } else {
            Err(HandshakeError::PeerRejected {
                reason: "initiator static key is not in our trust store".into(),
            })
        }
    })?;

    let session_id = transport.session_id().to_string();

    // Transport phase. Receive the initiator's message first, then reply.
    let frame = read_frame(&mut stream).await?;
    let mut decrypted = vec![0u8; frame.len()];
    let n = transport.receive(&frame, &mut decrypted)?;
    decrypted.truncate(n);

    let reply = b"hello back from the XX responder";
    let mut ciphertext = vec![0u8; reply.len() + Transport::<Channel>::OVERHEAD];
    let n = transport.send(reply, &mut ciphertext)?;
    write_frame(&mut stream, &ciphertext[..n]).await?;

    Ok((session_id, String::from_utf8(decrypted)?))
}

/// Write a single transport record with a 2-byte big-endian length prefix.
async fn write_frame(stream: &mut TcpStream, payload: &[u8]) -> Result<(), BoxError> {
    let len = u16::try_from(payload.len())?;
    stream.write_all(&len.to_be_bytes()).await?;
    stream.write_all(payload).await?;
    stream.flush().await?;
    Ok(())
}

/// Read a single length-prefixed transport record.
async fn read_frame(stream: &mut TcpStream) -> Result<Vec<u8>, BoxError> {
    let mut len_buf = [0u8; 2];
    stream.read_exact(&mut len_buf).await?;
    let len = u16::from_be_bytes(len_buf) as usize;
    let mut payload = vec![0u8; len];
    stream.read_exact(&mut payload).await?;
    Ok(payload)
}
